// <auto-generated> Generated from the legacy schema; the analyte columns are intentionally kept exactly as they were. </auto-generated>
using DiagnosticLabs.Domain.Lab.Reports;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace DiagnosticLabs.Infrastructure.Persistence.Configurations;

internal sealed class StoolFecalysisReportConfiguration : IEntityTypeConfiguration<StoolFecalysisReport>
{
    public void Configure(EntityTypeBuilder<StoolFecalysisReport> builder)
    {
        builder.ToTable("StoolFecalysisReports");
        builder.HasKey(e => e.LabReportId);
        builder.HasOne(e => e.LabReport).WithOne().HasForeignKey<StoolFecalysisReport>(e => e.LabReportId);
        builder.Property(e => e.Color).HasMaxLength(50);
        builder.Property(e => e.Consistency).HasMaxLength(50);
        builder.Property(e => e.Others).HasMaxLength(500);
        builder.Property(e => e.Wbc).HasMaxLength(50);
        builder.Property(e => e.Rbc).HasMaxLength(50);
        builder.Property(e => e.Bacteria).HasMaxLength(50);
        builder.Property(e => e.YeastCells).HasMaxLength(50);
        builder.Property(e => e.FatGlobules).HasMaxLength(50);
        builder.Property(e => e.OvaParasite).HasMaxLength(100);
        builder.Property(e => e.MedicalTechnologist2).HasMaxLength(100);
        builder.Property(e => e.Result).HasMaxLength(500);
    }
}

internal sealed class UrinalysisReportConfiguration : IEntityTypeConfiguration<UrinalysisReport>
{
    public void Configure(EntityTypeBuilder<UrinalysisReport> builder)
    {
        builder.ToTable("UrinalysisReports");
        builder.HasKey(e => e.LabReportId);
        builder.HasOne(e => e.LabReport).WithOne().HasForeignKey<UrinalysisReport>(e => e.LabReportId);
        builder.Property(e => e.Color).HasMaxLength(50);
        builder.Property(e => e.Appearance).HasMaxLength(50);
        builder.Property(e => e.Reaction).HasMaxLength(50);
        builder.Property(e => e.SPGravity).HasMaxLength(50);
        builder.Property(e => e.Albumin).HasMaxLength(50);
        builder.Property(e => e.Sugar).HasMaxLength(50);
        builder.Property(e => e.PusCells).HasMaxLength(50);
        builder.Property(e => e.RedCells).HasMaxLength(50);
        builder.Property(e => e.MucusThreads).HasMaxLength(50);
        builder.Property(e => e.EpithelialCells).HasMaxLength(50);
        builder.Property(e => e.AmorphousUratesPO4).HasMaxLength(50);
        builder.Property(e => e.Bacteria).HasMaxLength(50);
        builder.Property(e => e.Casts).HasMaxLength(50);
        builder.Property(e => e.Crystals).HasMaxLength(50);
        builder.Property(e => e.Others).HasMaxLength(500);
    }
}

internal sealed class HematologyReportConfiguration : IEntityTypeConfiguration<HematologyReport>
{
    public void Configure(EntityTypeBuilder<HematologyReport> builder)
    {
        builder.ToTable("HematologyReports");
        builder.HasKey(e => e.LabReportId);
        builder.HasOne(e => e.LabReport).WithOne().HasForeignKey<HematologyReport>(e => e.LabReportId);
        builder.Property(e => e.HematocritNValue).HasMaxLength(100);
        builder.Property(e => e.HematocritResult).HasMaxLength(100);
        builder.Property(e => e.HemoglobinNValue).HasMaxLength(100);
        builder.Property(e => e.HemoglobinResult).HasMaxLength(100);
        builder.Property(e => e.WBCCountNValue).HasMaxLength(100);
        builder.Property(e => e.WBCCountResult).HasMaxLength(100);
        builder.Property(e => e.SegmentersNValue).HasMaxLength(100);
        builder.Property(e => e.SegmentersResult).HasMaxLength(100);
        builder.Property(e => e.LymphocytesNValue).HasMaxLength(100);
        builder.Property(e => e.LymphocytesResult).HasMaxLength(100);
        builder.Property(e => e.EosinophilsNValue).HasMaxLength(100);
        builder.Property(e => e.EosinophilsResult).HasMaxLength(100);
        builder.Property(e => e.MonocytesNValue).HasMaxLength(100);
        builder.Property(e => e.MonocytesResult).HasMaxLength(100);
        builder.Property(e => e.BasophilsNValue).HasMaxLength(100);
        builder.Property(e => e.BasophilsResult).HasMaxLength(100);
        builder.Property(e => e.StabNValue).HasMaxLength(100);
        builder.Property(e => e.StabResult).HasMaxLength(100);
        builder.Property(e => e.PlateletCountNValue).HasMaxLength(100);
        builder.Property(e => e.PlateletCountResult).HasMaxLength(100);
    }
}

internal sealed class ImmunologyReportConfiguration : IEntityTypeConfiguration<ImmunologyReport>
{
    public void Configure(EntityTypeBuilder<ImmunologyReport> builder)
    {
        builder.ToTable("ImmunologyReports");
        builder.HasKey(e => e.LabReportId);
        builder.HasOne(e => e.LabReport).WithOne().HasForeignKey<ImmunologyReport>(e => e.LabReportId);
        builder.Property(e => e.Test).HasMaxLength(100);
        builder.Property(e => e.Result).HasMaxLength(500);
    }
}

internal sealed class SerologyReportConfiguration : IEntityTypeConfiguration<SerologyReport>
{
    public void Configure(EntityTypeBuilder<SerologyReport> builder)
    {
        builder.ToTable("SerologyReports");
        builder.HasKey(e => e.LabReportId);
        builder.HasOne(e => e.LabReport).WithOne().HasForeignKey<SerologyReport>(e => e.LabReportId);
        builder.Property(e => e.Test).HasMaxLength(100);
        builder.Property(e => e.Result).HasMaxLength(500);
    }
}

internal sealed class PregnancyTestReportConfiguration : IEntityTypeConfiguration<PregnancyTestReport>
{
    public void Configure(EntityTypeBuilder<PregnancyTestReport> builder)
    {
        builder.ToTable("PregnancyTestReports");
        builder.HasKey(e => e.LabReportId);
        builder.HasOne(e => e.LabReport).WithOne().HasForeignKey<PregnancyTestReport>(e => e.LabReportId);
        builder.Property(e => e.Result).HasMaxLength(500);
    }
}

internal sealed class ClinicalChemistryReportConfiguration : IEntityTypeConfiguration<ClinicalChemistryReport>
{
    public void Configure(EntityTypeBuilder<ClinicalChemistryReport> builder)
    {
        builder.ToTable("ClinicalChemistryReports");
        builder.HasKey(e => e.LabReportId);
        builder.HasOne(e => e.LabReport).WithOne().HasForeignKey<ClinicalChemistryReport>(e => e.LabReportId);
        builder.Property(e => e.FBSNValue).HasMaxLength(100);
        builder.Property(e => e.FBSResult).HasMaxLength(100);
        builder.Property(e => e.TotalCholesterolNValue).HasMaxLength(100);
        builder.Property(e => e.TotalCholesterolResult).HasMaxLength(100);
        builder.Property(e => e.TriglyceridesNValue).HasMaxLength(100);
        builder.Property(e => e.TriglyceridesResult).HasMaxLength(100);
        builder.Property(e => e.HDLNValue).HasMaxLength(100);
        builder.Property(e => e.HDLResult).HasMaxLength(100);
        builder.Property(e => e.BUNNValue).HasMaxLength(100);
        builder.Property(e => e.BUNResult).HasMaxLength(100);
        builder.Property(e => e.CreatinineNValue).HasMaxLength(100);
        builder.Property(e => e.CreatinineResult).HasMaxLength(100);
        builder.Property(e => e.BloodUricAcidNValue).HasMaxLength(100);
        builder.Property(e => e.BloodUricAcidResult).HasMaxLength(100);
        builder.Property(e => e.LDLNValue).HasMaxLength(100);
        builder.Property(e => e.LDLResult).HasMaxLength(100);
        builder.Property(e => e.SGPTNValue).HasMaxLength(100);
        builder.Property(e => e.SGPTResult).HasMaxLength(100);
    }
}

internal sealed class ClinicalChemistry1ReportConfiguration : IEntityTypeConfiguration<ClinicalChemistry1Report>
{
    public void Configure(EntityTypeBuilder<ClinicalChemistry1Report> builder)
    {
        builder.ToTable("ClinicalChemistry1Reports");
        builder.HasKey(e => e.LabReportId);
        builder.HasOne(e => e.LabReport).WithOne().HasForeignKey<ClinicalChemistry1Report>(e => e.LabReportId);
        builder.Property(e => e.Test).HasMaxLength(100);
        builder.Property(e => e.Result).HasMaxLength(500);
    }
}

internal sealed class ClinicalChemistry2ReportConfiguration : IEntityTypeConfiguration<ClinicalChemistry2Report>
{
    public void Configure(EntityTypeBuilder<ClinicalChemistry2Report> builder)
    {
        builder.ToTable("ClinicalChemistry2Reports");
        builder.HasKey(e => e.LabReportId);
        builder.HasOne(e => e.LabReport).WithOne().HasForeignKey<ClinicalChemistry2Report>(e => e.LabReportId);
        builder.Property(e => e.AlkalinePhosphataseCNValue).HasMaxLength(100);
        builder.Property(e => e.AlkalinePhosphataseCUnit).HasMaxLength(100);
        builder.Property(e => e.AlkalinePhosphataseCResults).HasMaxLength(100);
        builder.Property(e => e.AlkalinePhosphataseSNValue).HasMaxLength(100);
        builder.Property(e => e.AlkalinePhosphataseSUnit).HasMaxLength(100);
        builder.Property(e => e.AlkalinePhosphataseSResults).HasMaxLength(100);
        builder.Property(e => e.SGOTCNValue).HasMaxLength(100);
        builder.Property(e => e.SGOTCUnit).HasMaxLength(100);
        builder.Property(e => e.SGOTCResults).HasMaxLength(100);
        builder.Property(e => e.SGOTSNValue).HasMaxLength(100);
        builder.Property(e => e.SGOTSUnit).HasMaxLength(100);
        builder.Property(e => e.SGOTSResults).HasMaxLength(100);
    }
}

internal sealed class AnnualPhysicalExamReportConfiguration : IEntityTypeConfiguration<AnnualPhysicalExamReport>
{
    public void Configure(EntityTypeBuilder<AnnualPhysicalExamReport> builder)
    {
        builder.ToTable("AnnualPhysicalExamReports");
        builder.HasKey(e => e.LabReportId);
        builder.HasOne(e => e.LabReport).WithOne().HasForeignKey<AnnualPhysicalExamReport>(e => e.LabReportId);
        builder.Property(e => e.DepartmentOrAgency).HasMaxLength(100);
        builder.Property(e => e.CivilStatus).HasMaxLength(50);
        builder.Property(e => e.ContactNo).HasMaxLength(100);
        builder.Property(e => e.ENT).HasMaxLength(200);
        builder.Property(e => e.Gastroenterology).HasMaxLength(200);
        builder.Property(e => e.Respiratory).HasMaxLength(200);
        builder.Property(e => e.IntegumentarySkin).HasMaxLength(200);
        builder.Property(e => e.Cardiology).HasMaxLength(200);
        builder.Property(e => e.Psychology).HasMaxLength(200);
        builder.Property(e => e.Endocrinology).HasMaxLength(200);
        builder.Property(e => e.OBGyneUrology).HasMaxLength(200);
        builder.Property(e => e.Muscoloskeletal).HasMaxLength(200);
        builder.Property(e => e.InfectiousCommunicable).HasMaxLength(200);
        builder.Property(e => e.Neurological).HasMaxLength(200);
        builder.Property(e => e.Surgical).HasMaxLength(200);
        builder.Property(e => e.OthersPast).HasMaxLength(200);
        builder.Property(e => e.Medications).HasMaxLength(200);
        builder.Property(e => e.ReviewOfSystems).HasMaxLength(200);
        builder.Property(e => e.Allergies).HasMaxLength(200);
        builder.Property(e => e.SmokingSinceWhen).HasMaxLength(200);
        builder.Property(e => e.DrinkingSinceWhen).HasMaxLength(200);
        builder.Property(e => e.DrinkingFrequency).HasMaxLength(20);
        builder.Property(e => e.LMP).HasMaxLength(50);
        builder.Property(e => e.LMPType).HasMaxLength(50);
        builder.Property(e => e.BP1st).HasMaxLength(20);
        builder.Property(e => e.BP2nd).HasMaxLength(20);
        builder.Property(e => e.CardiacRate1st).HasMaxLength(20);
        builder.Property(e => e.CardiacRate2nd).HasMaxLength(20);
        builder.Property(e => e.Height).HasMaxLength(20);
        builder.Property(e => e.Weight).HasMaxLength(20);
        builder.Property(e => e.BMICategory).HasMaxLength(50);
        builder.Property(e => e.VARightEyeWGlasses).HasMaxLength(50);
        builder.Property(e => e.VARightEyeWOGlasses).HasMaxLength(50);
        builder.Property(e => e.VALeftEyeWGlasses).HasMaxLength(50);
        builder.Property(e => e.VALeftEyeWOGlasses).HasMaxLength(50);
        builder.Property(e => e.VisualAcuity).HasMaxLength(20);
        builder.Property(e => e.Skin).HasMaxLength(2);
        builder.Property(e => e.HeadScalp).HasMaxLength(2);
        builder.Property(e => e.Eyes).HasMaxLength(2);
        builder.Property(e => e.Ears).HasMaxLength(2);
        builder.Property(e => e.Nose).HasMaxLength(2);
        builder.Property(e => e.TeethTonsilsThroatPharynx).HasMaxLength(2);
        builder.Property(e => e.NeckLymphNodesThyroid).HasMaxLength(2);
        builder.Property(e => e.ThoraxBreast).HasMaxLength(2);
        builder.Property(e => e.HeartLungs).HasMaxLength(2);
        builder.Property(e => e.AbdomenLiverSpleen).HasMaxLength(2);
        builder.Property(e => e.InguinalAreaGenitalsAnus).HasMaxLength(2);
        builder.Property(e => e.ExtremetiesSpine).HasMaxLength(2);
        builder.Property(e => e.Tattoo).HasMaxLength(2);
        builder.Property(e => e.MassCyst).HasMaxLength(2);
        builder.Property(e => e.OthersPE).HasMaxLength(2);
        builder.Property(e => e.Findings).HasMaxLength(500);
        builder.Property(e => e.VitalSignsBy).HasMaxLength(50);
        builder.Property(e => e.HeightWeightBy).HasMaxLength(50);
    }
}

internal sealed class MedicalExaminationReportConfiguration : IEntityTypeConfiguration<MedicalExaminationReport>
{
    public void Configure(EntityTypeBuilder<MedicalExaminationReport> builder)
    {
        builder.ToTable("MedicalExaminationReports");
        builder.HasKey(e => e.LabReportId);
        builder.HasOne(e => e.LabReport).WithOne().HasForeignKey<MedicalExaminationReport>(e => e.LabReportId);
        builder.Property(e => e.ContactNo).HasMaxLength(100);
        builder.Property(e => e.CivilStatus).HasMaxLength(50);
        builder.Property(e => e.ChestXray).HasMaxLength(10);
        builder.Property(e => e.ChestXrayRemarks).HasMaxLength(100);
        builder.Property(e => e.CBC).HasMaxLength(10);
        builder.Property(e => e.CBCRemarks).HasMaxLength(100);
        builder.Property(e => e.Urinalysis).HasMaxLength(10);
        builder.Property(e => e.UrinalysisRemarks).HasMaxLength(100);
        builder.Property(e => e.Fecalysis).HasMaxLength(10);
        builder.Property(e => e.FecalysisRemarks).HasMaxLength(100);
        builder.Property(e => e.HBsAg).HasMaxLength(10);
        builder.Property(e => e.HBsAgRemarks).HasMaxLength(100);
        builder.Property(e => e.DrugTest2Panel).HasMaxLength(10);
        builder.Property(e => e.DrugTest2PanelRemarks).HasMaxLength(100);
        builder.Property(e => e.DrugTest4Panel).HasMaxLength(10);
        builder.Property(e => e.DrugTest4PanelRemarks).HasMaxLength(100);
        builder.Property(e => e.Classification).HasMaxLength(10);
        builder.Property(e => e.MedicalSurgicalHistory).HasMaxLength(500);
        builder.Property(e => e.Assessment).HasMaxLength(500);
        builder.Property(e => e.AssessmentDoneBy).HasMaxLength(250);
        builder.Property(e => e.PhysicianName).HasMaxLength(250);
        builder.Property(e => e.PhysicianLicense).HasMaxLength(250);
    }
}

