/*
  One-time data migration: legacy DiagnosticLabsDB -> new schema.
  GENERATED by tools/Generate-LegacyMigration.ps1 - do not edit by hand.

  Run against an EMPTY, freshly migrated target database (the legacy database is only read):

    sqlcmd -S <server> -d <target> -E -C -I -b -i db/migrate-from-legacy.sql ^
           -v Legacy=DiagnosticLabsDB LegacyTimeZone="Singapore Standard Time"

  Notes
   * Legacy timestamps are local time; they are converted to UTC using $(LegacyTimeZone) (a Windows time zone id).
   * Everything runs in one transaction; any error rolls the whole migration back.
   * Ids are preserved for every table except lab reports (merged into LabReports, new ids) and the
     WALK-IN company (legacy Id 0 is not allowed to stay 0).
   * Audit user ids that do not exist in Users (e.g. the legacy 0 placeholder) become NULL.
   * Lab rows from before the registration workflow (PatientRegistrationId = 0) keep their patient and get a NULL registration.
   * Lab rows whose patient cannot be found cannot satisfy the new foreign keys; they are skipped and listed at the end.
*/
SET NOCOUNT ON;
SET XACT_ABORT ON;

IF EXISTS (SELECT 1 FROM [Users]) OR EXISTS (SELECT 1 FROM [Patients]) OR EXISTS (SELECT 1 FROM [Modules])
    THROW 50000, 'Target database is not empty. Run this on a freshly migrated, empty database.', 1;

IF NOT EXISTS (SELECT 1 FROM sys.time_zone_info WHERE name = '$(LegacyTimeZone)')
    THROW 50001, 'LegacyTimeZone is not a valid Windows time zone id.', 1;

BEGIN TRANSACTION;

CREATE TABLE #u (Id bigint PRIMARY KEY);
INSERT INTO #u SELECT Id FROM [$(Legacy)].dbo.[Users];

CREATE TABLE #skipped (SourceTable sysname, LegacyId bigint, Reason nvarchar(200));
CREATE TABLE #map (LegacyId bigint PRIMARY KEY, NewId bigint NOT NULL);

-- Users -> Users
SET IDENTITY_INSERT [Users] ON;
INSERT INTO [Users] ([Id], [Username], [FullName], [PasswordHash], [IsAdmin], [MustChangePassword], [FailedLoginCount], [CreatedAtUtc], [CreatedByUserId], [UpdatedAtUtc], [UpdatedByUserId], [IsActive])
SELECT s.[Id],
        s.[Username],
        s.[FullName],
        s.[Password],
        s.IsAdmin,
        0,
        0,
        CAST(CAST(s.CreatedDate AS datetime2(3)) AT TIME ZONE '$(LegacyTimeZone)' AT TIME ZONE 'UTC' AS datetime2(3)),
        (SELECT u.Id FROM #u u WHERE u.Id = s.CreatedByUserId),
        CAST(CAST(s.UpdatedDate AS datetime2(3)) AT TIME ZONE '$(LegacyTimeZone)' AT TIME ZONE 'UTC' AS datetime2(3)),
        (SELECT u.Id FROM #u u WHERE u.Id = s.UpdatedByUserId),
        s.IsActive
FROM [$(Legacy)].dbo.[Users] s
;
SET IDENTITY_INSERT [Users] OFF;

-- ModuleTypes -> ModuleTypes
INSERT INTO [ModuleTypes] ([Id], [ModuleTypeName], [Icon], [SortOrder], [IsActive], [IsAdmin])
SELECT s.[Id],
        s.[ModuleTypeName],
        s.[Icon],
        s.[SortOrder],
        s.[IsActive],
        s.[IsAdmin]
FROM [$(Legacy)].dbo.[ModuleTypes] s
;

-- Services -> Services
SET IDENTITY_INSERT [Services] ON;
INSERT INTO [Services] ([Id], [ServiceName], [ServiceDescription], [Price], [CreatedAtUtc], [CreatedByUserId], [UpdatedAtUtc], [UpdatedByUserId], [IsActive])
SELECT s.[Id],
        s.[ServiceName],
        s.[ServiceDescription],
        s.[Price],
        CAST(CAST(s.CreatedDate AS datetime2(3)) AT TIME ZONE '$(LegacyTimeZone)' AT TIME ZONE 'UTC' AS datetime2(3)),
        (SELECT u.Id FROM #u u WHERE u.Id = s.CreatedByUserId),
        CAST(CAST(s.UpdatedDate AS datetime2(3)) AT TIME ZONE '$(LegacyTimeZone)' AT TIME ZONE 'UTC' AS datetime2(3)),
        (SELECT u.Id FROM #u u WHERE u.Id = s.UpdatedByUserId),
        s.IsActive
FROM [$(Legacy)].dbo.[Services] s
;
SET IDENTITY_INSERT [Services] OFF;

-- Modules -> Modules
INSERT INTO [Modules] ([Id], [ModuleTypeId], [ModuleName], [HasView], [HasCreate], [HasEdit], [HasDelete], [HasSearch], [HasPrint], [HasShowList], [HasSetDefaults], [Icon], [SortOrder], [IsActive], [ServiceId])
SELECT s.[Id],
        s.[ModuleTypeId],
        s.[ModuleName],
        s.[HasView],
        s.[HasCreate],
        s.[HasEdit],
        s.[HasDelete],
        s.[HasSearch],
        s.[HasPrint],
        s.[HasShowList],
        s.[HasSetDefaults],
        s.[Icon],
        s.[SortOrder],
        s.[IsActive],
        s.[ServiceId]
FROM [$(Legacy)].dbo.[Modules] s
;

-- UserPermissions -> UserPermissions
SET IDENTITY_INSERT [UserPermissions] ON;
INSERT INTO [UserPermissions] ([Id], [UserId], [ModuleId], [AllowCreate], [AllowEdit], [AllowDelete], [AllowPrint], [CreatedAtUtc], [CreatedByUserId], [UpdatedAtUtc], [UpdatedByUserId])
SELECT s.[Id],
        s.[UserId],
        s.[ModuleId],
        CASE WHEN s.ViewOnly = 1 THEN 0 ELSE s.[AllowCreate] END,
        CASE WHEN s.ViewOnly = 1 THEN 0 ELSE s.[AllowEdit] END,
        CASE WHEN s.ViewOnly = 1 THEN 0 ELSE s.[AllowDelete] END,
        CASE WHEN s.ViewOnly = 1 THEN 0 ELSE s.[AllowPrint] END,
        CAST(CAST(s.CreatedDate AS datetime2(3)) AT TIME ZONE '$(LegacyTimeZone)' AT TIME ZONE 'UTC' AS datetime2(3)),
        (SELECT u.Id FROM #u u WHERE u.Id = s.CreatedByUserId),
        CAST(CAST(s.UpdatedDate AS datetime2(3)) AT TIME ZONE '$(LegacyTimeZone)' AT TIME ZONE 'UTC' AS datetime2(3)),
        (SELECT u.Id FROM #u u WHERE u.Id = s.UpdatedByUserId)
FROM [$(Legacy)].dbo.[UserPermissions] s
WHERE s.ViewOnly = 1 OR s.AllowCreate = 1 OR s.AllowEdit = 1 OR s.AllowDelete = 1 OR s.AllowPrint = 1
;
SET IDENTITY_INSERT [UserPermissions] OFF;

-- Companies -> Companies
SET IDENTITY_INSERT [Companies] ON;
INSERT INTO [Companies] ([Id], [CompanyName], [Address], [ContactNumbers], [ContactPerson], [CreatedAtUtc], [CreatedByUserId], [UpdatedAtUtc], [UpdatedByUserId], [IsActive])
SELECT s.[Id],
        s.[CompanyName],
        s.[Address],
        s.[ContactNumbers],
        s.[ContactPerson],
        CAST(CAST(s.CreatedDate AS datetime2(3)) AT TIME ZONE '$(LegacyTimeZone)' AT TIME ZONE 'UTC' AS datetime2(3)),
        (SELECT u.Id FROM #u u WHERE u.Id = s.CreatedByUserId),
        CAST(CAST(s.UpdatedDate AS datetime2(3)) AT TIME ZONE '$(LegacyTimeZone)' AT TIME ZONE 'UTC' AS datetime2(3)),
        (SELECT u.Id FROM #u u WHERE u.Id = s.UpdatedByUserId),
        s.IsActive
FROM [$(Legacy)].dbo.[Companies] s
WHERE s.Id <> 0
;
SET IDENTITY_INSERT [Companies] OFF;

-- CompanySetups -> CompanySetups
SET IDENTITY_INSERT [CompanySetups] ON;
INSERT INTO [CompanySetups] ([Id], [CompanyName], [SubCompanyName], [Tagline], [Address], [ContactNumbers], [Email], [Code], [Logo], [CreatedAtUtc], [CreatedByUserId], [UpdatedAtUtc], [UpdatedByUserId])
SELECT s.Id,
        s.[CompanyName],
        s.[SubCompanyName],
        s.[Tagline],
        s.[Address],
        s.[ContactNumbers],
        s.[Email],
        s.[Code],
        s.[Logo],
        CAST(CAST(s.UpdatedDate AS datetime2(3)) AT TIME ZONE '$(LegacyTimeZone)' AT TIME ZONE 'UTC' AS datetime2(3)),
        (SELECT u.Id FROM #u u WHERE u.Id = s.UpdatedByUserId),
        CAST(CAST(s.UpdatedDate AS datetime2(3)) AT TIME ZONE '$(LegacyTimeZone)' AT TIME ZONE 'UTC' AS datetime2(3)),
        (SELECT u.Id FROM #u u WHERE u.Id = s.UpdatedByUserId)
FROM [$(Legacy)].dbo.[CompanySetups] s
;
SET IDENTITY_INSERT [CompanySetups] OFF;

-- Departments -> Departments
SET IDENTITY_INSERT [Departments] ON;
INSERT INTO [Departments] ([Id], [DepartmentName], [DepartmentDescription], [CreatedAtUtc], [CreatedByUserId], [UpdatedAtUtc], [UpdatedByUserId], [IsActive])
SELECT s.[Id],
        s.[DepartmentName],
        s.[DepartmentDescription],
        CAST(CAST(s.CreatedDate AS datetime2(3)) AT TIME ZONE '$(LegacyTimeZone)' AT TIME ZONE 'UTC' AS datetime2(3)),
        (SELECT u.Id FROM #u u WHERE u.Id = s.CreatedByUserId),
        CAST(CAST(s.UpdatedDate AS datetime2(3)) AT TIME ZONE '$(LegacyTimeZone)' AT TIME ZONE 'UTC' AS datetime2(3)),
        (SELECT u.Id FROM #u u WHERE u.Id = s.UpdatedByUserId),
        s.IsActive
FROM [$(Legacy)].dbo.[Departments] s
;
SET IDENTITY_INSERT [Departments] OFF;

-- Items -> Items
SET IDENTITY_INSERT [Items] ON;
INSERT INTO [Items] ([Id], [ItemName], [Cost], [CreatedAtUtc], [CreatedByUserId], [UpdatedAtUtc], [UpdatedByUserId], [IsActive])
SELECT s.[Id],
        s.[ItemName],
        s.[Cost],
        CAST(CAST(s.CreatedDate AS datetime2(3)) AT TIME ZONE '$(LegacyTimeZone)' AT TIME ZONE 'UTC' AS datetime2(3)),
        (SELECT u.Id FROM #u u WHERE u.Id = s.CreatedByUserId),
        CAST(CAST(s.UpdatedDate AS datetime2(3)) AT TIME ZONE '$(LegacyTimeZone)' AT TIME ZONE 'UTC' AS datetime2(3)),
        (SELECT u.Id FROM #u u WHERE u.Id = s.UpdatedByUserId),
        s.IsActive
FROM [$(Legacy)].dbo.[Items] s
;
SET IDENTITY_INSERT [Items] OFF;

-- ItemLocations -> ItemLocations
SET IDENTITY_INSERT [ItemLocations] ON;
INSERT INTO [ItemLocations] ([Id], [ItemLocationName], [CreatedAtUtc], [CreatedByUserId], [UpdatedAtUtc], [UpdatedByUserId], [IsActive])
SELECT s.[Id],
        s.[ItemLocationName],
        CAST(CAST(s.CreatedDate AS datetime2(3)) AT TIME ZONE '$(LegacyTimeZone)' AT TIME ZONE 'UTC' AS datetime2(3)),
        (SELECT u.Id FROM #u u WHERE u.Id = s.CreatedByUserId),
        CAST(CAST(s.UpdatedDate AS datetime2(3)) AT TIME ZONE '$(LegacyTimeZone)' AT TIME ZONE 'UTC' AS datetime2(3)),
        (SELECT u.Id FROM #u u WHERE u.Id = s.UpdatedByUserId),
        s.IsActive
FROM [$(Legacy)].dbo.[ItemLocations] s
;
SET IDENTITY_INSERT [ItemLocations] OFF;

-- ItemQuantities -> ItemQuantities
SET IDENTITY_INSERT [ItemQuantities] ON;
INSERT INTO [ItemQuantities] ([Id], [ItemId], [ItemLocationId], [Quantity], [CreatedAtUtc], [CreatedByUserId], [UpdatedAtUtc], [UpdatedByUserId], [IsDeleted], [DeletedAtUtc], [DeletedByUserId])
SELECT s.[Id],
        s.[ItemId],
        s.[ItemLocationId],
        s.[Quantity],
        CAST(CAST(s.CreatedDate AS datetime2(3)) AT TIME ZONE '$(LegacyTimeZone)' AT TIME ZONE 'UTC' AS datetime2(3)),
        (SELECT u.Id FROM #u u WHERE u.Id = s.CreatedByUserId),
        CAST(CAST(s.UpdatedDate AS datetime2(3)) AT TIME ZONE '$(LegacyTimeZone)' AT TIME ZONE 'UTC' AS datetime2(3)),
        (SELECT u.Id FROM #u u WHERE u.Id = s.UpdatedByUserId),
        CASE WHEN s.IsActive = 1 THEN 0 ELSE 1 END,
        CASE WHEN s.IsActive = 0 THEN CAST(CAST(s.UpdatedDate AS datetime2(3)) AT TIME ZONE '$(LegacyTimeZone)' AT TIME ZONE 'UTC' AS datetime2(3)) END,
        CASE WHEN s.IsActive = 0 THEN (SELECT u.Id FROM #u u WHERE u.Id = s.UpdatedByUserId) END
FROM [$(Legacy)].dbo.[ItemQuantities] s
;
SET IDENTITY_INSERT [ItemQuantities] OFF;

-- ServiceItemQuantities -> ServiceItemQuantities
SET IDENTITY_INSERT [ServiceItemQuantities] ON;
INSERT INTO [ServiceItemQuantities] ([Id], [ServiceId], [ItemId], [Quantity], [CreatedAtUtc], [CreatedByUserId], [UpdatedAtUtc], [UpdatedByUserId], [IsDeleted], [DeletedAtUtc], [DeletedByUserId])
SELECT s.[Id],
        s.[ServiceId],
        s.[ItemId],
        s.[Quantity],
        CAST(CAST(s.CreatedDate AS datetime2(3)) AT TIME ZONE '$(LegacyTimeZone)' AT TIME ZONE 'UTC' AS datetime2(3)),
        (SELECT u.Id FROM #u u WHERE u.Id = s.CreatedByUserId),
        CAST(CAST(s.UpdatedDate AS datetime2(3)) AT TIME ZONE '$(LegacyTimeZone)' AT TIME ZONE 'UTC' AS datetime2(3)),
        (SELECT u.Id FROM #u u WHERE u.Id = s.UpdatedByUserId),
        CASE WHEN s.IsActive = 1 THEN 0 ELSE 1 END,
        CASE WHEN s.IsActive = 0 THEN CAST(CAST(s.UpdatedDate AS datetime2(3)) AT TIME ZONE '$(LegacyTimeZone)' AT TIME ZONE 'UTC' AS datetime2(3)) END,
        CASE WHEN s.IsActive = 0 THEN (SELECT u.Id FROM #u u WHERE u.Id = s.UpdatedByUserId) END
FROM [$(Legacy)].dbo.[ServiceItemQuantities] s
;
SET IDENTITY_INSERT [ServiceItemQuantities] OFF;

-- Discounts -> Discounts
SET IDENTITY_INSERT [Discounts] ON;
INSERT INTO [Discounts] ([Id], [DiscountName], [DiscountDescription], [CreatedAtUtc], [CreatedByUserId], [UpdatedAtUtc], [UpdatedByUserId], [IsActive])
SELECT s.[Id],
        s.[DiscountName],
        s.[DiscountDescription],
        CAST(CAST(s.CreatedDate AS datetime2(3)) AT TIME ZONE '$(LegacyTimeZone)' AT TIME ZONE 'UTC' AS datetime2(3)),
        (SELECT u.Id FROM #u u WHERE u.Id = s.CreatedByUserId),
        CAST(CAST(s.UpdatedDate AS datetime2(3)) AT TIME ZONE '$(LegacyTimeZone)' AT TIME ZONE 'UTC' AS datetime2(3)),
        (SELECT u.Id FROM #u u WHERE u.Id = s.UpdatedByUserId),
        s.IsActive
FROM [$(Legacy)].dbo.[Discounts] s
;
SET IDENTITY_INSERT [Discounts] OFF;

-- DiscountDetails -> DiscountDetails
SET IDENTITY_INSERT [DiscountDetails] ON;
INSERT INTO [DiscountDetails] ([Id], [DiscountId], [Amount], [Percentage], [CreatedAtUtc], [CreatedByUserId], [UpdatedAtUtc], [UpdatedByUserId], [IsDeleted], [DeletedAtUtc], [DeletedByUserId])
SELECT s.[Id],
        s.[DiscountId],
        s.[Amount],
        s.[Percentage],
        CAST(CAST(s.CreatedDate AS datetime2(3)) AT TIME ZONE '$(LegacyTimeZone)' AT TIME ZONE 'UTC' AS datetime2(3)),
        (SELECT u.Id FROM #u u WHERE u.Id = s.CreatedByUserId),
        CAST(CAST(s.UpdatedDate AS datetime2(3)) AT TIME ZONE '$(LegacyTimeZone)' AT TIME ZONE 'UTC' AS datetime2(3)),
        (SELECT u.Id FROM #u u WHERE u.Id = s.UpdatedByUserId),
        CASE WHEN s.IsActive = 1 THEN 0 ELSE 1 END,
        CASE WHEN s.IsActive = 0 THEN CAST(CAST(s.UpdatedDate AS datetime2(3)) AT TIME ZONE '$(LegacyTimeZone)' AT TIME ZONE 'UTC' AS datetime2(3)) END,
        CASE WHEN s.IsActive = 0 THEN (SELECT u.Id FROM #u u WHERE u.Id = s.UpdatedByUserId) END
FROM [$(Legacy)].dbo.[DiscountDetails] s
;
SET IDENTITY_INSERT [DiscountDetails] OFF;

-- Packages -> Packages
SET IDENTITY_INSERT [Packages] ON;
INSERT INTO [Packages] ([Id], [PackageName], [PackageDescription], [Price], [CompanyId], [CreatedAtUtc], [CreatedByUserId], [UpdatedAtUtc], [UpdatedByUserId], [IsActive])
SELECT s.[Id],
        s.[PackageName],
        s.[PackageDescription],
        s.[Price],
        NULLIF(s.CompanyId, 0),
        CAST(CAST(s.CreatedDate AS datetime2(3)) AT TIME ZONE '$(LegacyTimeZone)' AT TIME ZONE 'UTC' AS datetime2(3)),
        (SELECT u.Id FROM #u u WHERE u.Id = s.CreatedByUserId),
        CAST(CAST(s.UpdatedDate AS datetime2(3)) AT TIME ZONE '$(LegacyTimeZone)' AT TIME ZONE 'UTC' AS datetime2(3)),
        (SELECT u.Id FROM #u u WHERE u.Id = s.UpdatedByUserId),
        s.IsActive
FROM [$(Legacy)].dbo.[Packages] s
;
SET IDENTITY_INSERT [Packages] OFF;

-- PackageServices -> PackageServices
SET IDENTITY_INSERT [PackageServices] ON;
INSERT INTO [PackageServices] ([Id], [PackageId], [ServiceId], [Price], [CreatedAtUtc], [CreatedByUserId], [UpdatedAtUtc], [UpdatedByUserId], [IsDeleted], [DeletedAtUtc], [DeletedByUserId])
SELECT s.[Id],
        s.[PackageId],
        s.[ServiceId],
        s.[Price],
        CAST(CAST(s.CreatedDate AS datetime2(3)) AT TIME ZONE '$(LegacyTimeZone)' AT TIME ZONE 'UTC' AS datetime2(3)),
        (SELECT u.Id FROM #u u WHERE u.Id = s.CreatedByUserId),
        CAST(CAST(s.UpdatedDate AS datetime2(3)) AT TIME ZONE '$(LegacyTimeZone)' AT TIME ZONE 'UTC' AS datetime2(3)),
        (SELECT u.Id FROM #u u WHERE u.Id = s.UpdatedByUserId),
        CASE WHEN s.IsActive = 1 THEN 0 ELSE 1 END,
        CASE WHEN s.IsActive = 0 THEN CAST(CAST(s.UpdatedDate AS datetime2(3)) AT TIME ZONE '$(LegacyTimeZone)' AT TIME ZONE 'UTC' AS datetime2(3)) END,
        CASE WHEN s.IsActive = 0 THEN (SELECT u.Id FROM #u u WHERE u.Id = s.UpdatedByUserId) END
FROM [$(Legacy)].dbo.[PackageServices] s
;
SET IDENTITY_INSERT [PackageServices] OFF;

-- DefaultValues -> LookupValues
INSERT INTO [LookupValues] ([ModuleId], [Kind], [FieldName], [Title], [Value], [CreatedAtUtc], [CreatedByUserId], [UpdatedAtUtc], [UpdatedByUserId], [IsActive])
SELECT s.ModuleId,
        1,
        s.FieldName,
        s.FieldValueTitle,
        s.FieldValue,
        CAST(CAST(s.CreatedDate AS datetime2(3)) AT TIME ZONE '$(LegacyTimeZone)' AT TIME ZONE 'UTC' AS datetime2(3)),
        (SELECT u.Id FROM #u u WHERE u.Id = s.CreatedByUserId),
        CAST(CAST(s.UpdatedDate AS datetime2(3)) AT TIME ZONE '$(LegacyTimeZone)' AT TIME ZONE 'UTC' AS datetime2(3)),
        (SELECT u.Id FROM #u u WHERE u.Id = s.UpdatedByUserId),
        s.IsActive
FROM [$(Legacy)].dbo.[DefaultValues] s
;

-- SingleLineEntries -> LookupValues
INSERT INTO [LookupValues] ([ModuleId], [Kind], [FieldName], [Title], [Value], [CreatedAtUtc], [CreatedByUserId], [UpdatedAtUtc], [UpdatedByUserId], [IsActive])
SELECT s.ModuleId,
        2,
        s.FieldName,
        NULL,
        s.FieldValue,
        CAST(CAST(s.CreatedDate AS datetime2(3)) AT TIME ZONE '$(LegacyTimeZone)' AT TIME ZONE 'UTC' AS datetime2(3)),
        (SELECT u.Id FROM #u u WHERE u.Id = s.CreatedByUserId),
        CAST(CAST(s.UpdatedDate AS datetime2(3)) AT TIME ZONE '$(LegacyTimeZone)' AT TIME ZONE 'UTC' AS datetime2(3)),
        (SELECT u.Id FROM #u u WHERE u.Id = s.UpdatedByUserId),
        s.IsActive
FROM [$(Legacy)].dbo.[SingleLineEntries] s
;

-- MultiLineEntries -> LookupValues
INSERT INTO [LookupValues] ([ModuleId], [Kind], [FieldName], [Title], [Value], [CreatedAtUtc], [CreatedByUserId], [UpdatedAtUtc], [UpdatedByUserId], [IsActive])
SELECT s.ModuleId,
        3,
        s.FieldName,
        s.FieldValueTitle,
        s.FieldValue,
        CAST(CAST(s.CreatedDate AS datetime2(3)) AT TIME ZONE '$(LegacyTimeZone)' AT TIME ZONE 'UTC' AS datetime2(3)),
        (SELECT u.Id FROM #u u WHERE u.Id = s.CreatedByUserId),
        CAST(CAST(s.UpdatedDate AS datetime2(3)) AT TIME ZONE '$(LegacyTimeZone)' AT TIME ZONE 'UTC' AS datetime2(3)),
        (SELECT u.Id FROM #u u WHERE u.Id = s.UpdatedByUserId),
        s.IsActive
FROM [$(Legacy)].dbo.[MultiLineEntries] s
;

-- LabResultsDefaults -> ModuleDefaults
INSERT INTO [ModuleDefaults] ([ModuleId], [Defaults], [CreatedAtUtc], [CreatedByUserId], [UpdatedAtUtc], [UpdatedByUserId], [IsActive])
SELECT s.ModuleId,
        s.Defaults,
        CAST(CAST(s.CreatedDate AS datetime2(3)) AT TIME ZONE '$(LegacyTimeZone)' AT TIME ZONE 'UTC' AS datetime2(3)),
        (SELECT u.Id FROM #u u WHERE u.Id = s.CreatedByUserId),
        CAST(CAST(s.UpdatedDate AS datetime2(3)) AT TIME ZONE '$(LegacyTimeZone)' AT TIME ZONE 'UTC' AS datetime2(3)),
        (SELECT u.Id FROM #u u WHERE u.Id = s.UpdatedByUserId),
        s.IsActive
FROM [$(Legacy)].dbo.[LabResultsDefaults] s
;

-- Patients -> Patients
SET IDENTITY_INSERT [Patients] ON;
INSERT INTO [Patients] ([Id], [PatientCode], [PatientName], [DateOfBirth], [Age], [Sex], [CivilStatus], [Address], [ContactNumbers], [CreatedAtUtc], [CreatedByUserId], [UpdatedAtUtc], [UpdatedByUserId], [IsDeleted], [DeletedAtUtc], [DeletedByUserId])
SELECT s.[Id],
        s.[PatientCode],
        s.[PatientName],
        CAST(s.DateOfBirth AS date),
        NULLIF(LTRIM(RTRIM(CASE WHEN s.DateOfBirth IS NULL THEN s.Age END)), ''),
        s.Gender,
        s.CivilStatus,
        s.Address,
        s.ContactNumbers,
        CAST(CAST(s.CreatedDate AS datetime2(3)) AT TIME ZONE '$(LegacyTimeZone)' AT TIME ZONE 'UTC' AS datetime2(3)),
        (SELECT u.Id FROM #u u WHERE u.Id = s.CreatedByUserId),
        CAST(CAST(s.UpdatedDate AS datetime2(3)) AT TIME ZONE '$(LegacyTimeZone)' AT TIME ZONE 'UTC' AS datetime2(3)),
        (SELECT u.Id FROM #u u WHERE u.Id = s.UpdatedByUserId),
        CASE WHEN s.IsActive = 1 THEN 0 ELSE 1 END,
        CASE WHEN s.IsActive = 0 THEN CAST(CAST(s.UpdatedDate AS datetime2(3)) AT TIME ZONE '$(LegacyTimeZone)' AT TIME ZONE 'UTC' AS datetime2(3)) END,
        CASE WHEN s.IsActive = 0 THEN (SELECT u.Id FROM #u u WHERE u.Id = s.UpdatedByUserId) END
FROM [$(Legacy)].dbo.[Patients] s
;
SET IDENTITY_INSERT [Patients] OFF;

-- PatientRegistrations -> PatientRegistrations
SET IDENTITY_INSERT [PatientRegistrations] ON;
INSERT INTO [PatientRegistrations] ([Id], [RegistrationCode], [InputDate], [PatientId], [CompanyId], [PackageId], [BatchName], [AmountDue], [DiscountAmount], [DiscountPercentage], [DiscountTotal], [CreatedAtUtc], [CreatedByUserId], [UpdatedAtUtc], [UpdatedByUserId], [IsDeleted], [DeletedAtUtc], [DeletedByUserId])
SELECT s.[Id],
        s.[RegistrationCode],
        CAST(CAST(s.InputDate AS datetime2(3)) AT TIME ZONE '$(LegacyTimeZone)' AT TIME ZONE 'UTC' AS datetime2(3)),
        s.[PatientId],
        NULLIF(s.CompanyId, 0),
        NULLIF(s.PackageId, 0),
        s.[BatchName],
        s.[AmountDue],
        s.[DiscountAmount],
        s.[DiscountPercentage],
        s.[DiscountTotal],
        CAST(CAST(s.CreatedDate AS datetime2(3)) AT TIME ZONE '$(LegacyTimeZone)' AT TIME ZONE 'UTC' AS datetime2(3)),
        (SELECT u.Id FROM #u u WHERE u.Id = s.CreatedByUserId),
        CAST(CAST(s.UpdatedDate AS datetime2(3)) AT TIME ZONE '$(LegacyTimeZone)' AT TIME ZONE 'UTC' AS datetime2(3)),
        (SELECT u.Id FROM #u u WHERE u.Id = s.UpdatedByUserId),
        CASE WHEN s.IsActive = 1 THEN 0 ELSE 1 END,
        CASE WHEN s.IsActive = 0 THEN CAST(CAST(s.UpdatedDate AS datetime2(3)) AT TIME ZONE '$(LegacyTimeZone)' AT TIME ZONE 'UTC' AS datetime2(3)) END,
        CASE WHEN s.IsActive = 0 THEN (SELECT u.Id FROM #u u WHERE u.Id = s.UpdatedByUserId) END
FROM [$(Legacy)].dbo.[PatientRegistrations] s
;
SET IDENTITY_INSERT [PatientRegistrations] OFF;

-- PatientRegistrationServices -> PatientRegistrationServices
SET IDENTITY_INSERT [PatientRegistrationServices] ON;
INSERT INTO [PatientRegistrationServices] ([Id], [PatientRegistrationId], [ServiceId], [Price], [CreatedAtUtc], [CreatedByUserId], [UpdatedAtUtc], [UpdatedByUserId], [IsDeleted], [DeletedAtUtc], [DeletedByUserId])
SELECT s.[Id],
        s.[PatientRegistrationId],
        s.[ServiceId],
        s.[Price],
        CAST(CAST(s.CreatedDate AS datetime2(3)) AT TIME ZONE '$(LegacyTimeZone)' AT TIME ZONE 'UTC' AS datetime2(3)),
        (SELECT u.Id FROM #u u WHERE u.Id = s.CreatedByUserId),
        CAST(CAST(s.UpdatedDate AS datetime2(3)) AT TIME ZONE '$(LegacyTimeZone)' AT TIME ZONE 'UTC' AS datetime2(3)),
        (SELECT u.Id FROM #u u WHERE u.Id = s.UpdatedByUserId),
        CASE WHEN s.IsActive = 1 THEN 0 ELSE 1 END,
        CASE WHEN s.IsActive = 0 THEN CAST(CAST(s.UpdatedDate AS datetime2(3)) AT TIME ZONE '$(LegacyTimeZone)' AT TIME ZONE 'UTC' AS datetime2(3)) END,
        CASE WHEN s.IsActive = 0 THEN (SELECT u.Id FROM #u u WHERE u.Id = s.UpdatedByUserId) END
FROM [$(Legacy)].dbo.[PatientRegistrationServices] s
;
SET IDENTITY_INSERT [PatientRegistrationServices] OFF;

-- Payments -> Payments
SET IDENTITY_INSERT [Payments] ON;
INSERT INTO [Payments] ([Id], [PaymentDate], [PatientRegistrationId], [PaymentAmount], [Type], [CreatedAtUtc], [CreatedByUserId], [UpdatedAtUtc], [UpdatedByUserId], [IsDeleted], [DeletedAtUtc], [DeletedByUserId])
SELECT s.[Id],
        CAST(CAST(s.PaymentDate AS datetime2(3)) AT TIME ZONE '$(LegacyTimeZone)' AT TIME ZONE 'UTC' AS datetime2(3)),
        s.PatientRegistrationId,
        s.PaymentAmount,
        CASE WHEN s.IsCharge = 1 THEN 1 ELSE 0 END,
        CAST(CAST(s.CreatedDate AS datetime2(3)) AT TIME ZONE '$(LegacyTimeZone)' AT TIME ZONE 'UTC' AS datetime2(3)),
        (SELECT u.Id FROM #u u WHERE u.Id = s.CreatedByUserId),
        CAST(CAST(s.UpdatedDate AS datetime2(3)) AT TIME ZONE '$(LegacyTimeZone)' AT TIME ZONE 'UTC' AS datetime2(3)),
        (SELECT u.Id FROM #u u WHERE u.Id = s.UpdatedByUserId),
        CASE WHEN s.IsActive = 1 THEN 0 ELSE 1 END,
        CASE WHEN s.IsActive = 0 THEN CAST(CAST(s.UpdatedDate AS datetime2(3)) AT TIME ZONE '$(LegacyTimeZone)' AT TIME ZONE 'UTC' AS datetime2(3)) END,
        CASE WHEN s.IsActive = 0 THEN (SELECT u.Id FROM #u u WHERE u.Id = s.UpdatedByUserId) END
FROM [$(Legacy)].dbo.[Payments] s
;
SET IDENTITY_INSERT [Payments] OFF;

-- LatestCodeNumbers view -> CodeSequences (keeps the next registration number per prefix)
INSERT INTO [CodeSequences] ([Prefix], [LastNumber])
SELECT Prefix, MaxNumber FROM [$(Legacy)].dbo.[LatestCodeNumbers];

-- ===== Lab reports: header rows go to LabReports (new ids, mapped per source table) =====

-- StoolFecalyses -> LabReports (StoolFecalysis) + StoolFecalysisReports
TRUNCATE TABLE #map;
MERGE [LabReports] AS t
USING (
    SELECT s.Id AS LegacyId,
           COALESCE(s.PatientId, r.PatientId) AS PatientId,
           r.Id AS PatientRegistrationId,
           s.PatientCode,
           s.PatientName,
           s.Age,
           s.Sex,
           s.CompanyOrPhysician,
           COALESCE(CAST(CAST(s.DateRequested AS datetime2(3)) AT TIME ZONE '$(LegacyTimeZone)' AT TIME ZONE 'UTC' AS datetime2(3)), CAST(CAST(s.CreatedDate AS datetime2(3)) AT TIME ZONE '$(LegacyTimeZone)' AT TIME ZONE 'UTC' AS datetime2(3))) AS DateRequested,
           s.Remarks,
           s.MedicalTechnologist,
           s.Pathologist,
           CAST(CAST(s.CreatedDate AS datetime2(3)) AT TIME ZONE '$(LegacyTimeZone)' AT TIME ZONE 'UTC' AS datetime2(3)) AS CreatedAtUtc,
           (SELECT u.Id FROM #u u WHERE u.Id = s.CreatedByUserId) AS CreatedByUserId,
           CAST(CAST(s.UpdatedDate AS datetime2(3)) AT TIME ZONE '$(LegacyTimeZone)' AT TIME ZONE 'UTC' AS datetime2(3)) AS UpdatedAtUtc,
           (SELECT u.Id FROM #u u WHERE u.Id = s.UpdatedByUserId) AS UpdatedByUserId,
           CASE WHEN s.IsActive = 1 THEN 0 ELSE 1 END AS IsDeleted,
           CASE WHEN s.IsActive = 0 THEN CAST(CAST(s.UpdatedDate AS datetime2(3)) AT TIME ZONE '$(LegacyTimeZone)' AT TIME ZONE 'UTC' AS datetime2(3)) END AS DeletedAtUtc,
           CASE WHEN s.IsActive = 0 THEN (SELECT u.Id FROM #u u WHERE u.Id = s.UpdatedByUserId) END AS DeletedByUserId
    FROM [$(Legacy)].dbo.[StoolFecalyses] s
    LEFT JOIN [$(Legacy)].dbo.[PatientRegistrations] r ON r.Id = s.PatientRegistrationId
    JOIN [$(Legacy)].dbo.[Patients] p ON p.Id = COALESCE(s.PatientId, r.PatientId)
) AS src ON 1 = 0
WHEN NOT MATCHED THEN INSERT ([ReportType], [PatientId], [PatientRegistrationId], [PatientCode], [PatientName], [Age], [Sex], [CompanyOrPhysician], [DateRequested], [Remarks], [MedicalTechnologist], [Pathologist], [CreatedAtUtc], [CreatedByUserId], [UpdatedAtUtc], [UpdatedByUserId], [IsDeleted], [DeletedAtUtc], [DeletedByUserId])
    VALUES ('StoolFecalysis', src.PatientId, src.PatientRegistrationId, src.PatientCode, src.PatientName, src.Age, src.Sex, src.CompanyOrPhysician, src.DateRequested, src.Remarks, src.MedicalTechnologist, src.Pathologist, src.CreatedAtUtc, src.CreatedByUserId, src.UpdatedAtUtc, src.UpdatedByUserId, src.IsDeleted, src.DeletedAtUtc, src.DeletedByUserId)
OUTPUT src.LegacyId, inserted.Id INTO #map (LegacyId, NewId);

INSERT INTO #skipped SELECT 'StoolFecalyses', s.Id, 'No matching patient for this lab row' FROM [$(Legacy)].dbo.[StoolFecalyses] s WHERE s.Id NOT IN (SELECT LegacyId FROM #map);

INSERT INTO [LabReportPhotos] ([LabReportId], [Content]) SELECT m.NewId, s.Photo FROM [$(Legacy)].dbo.[StoolFecalyses] s JOIN #map m ON m.LegacyId = s.Id WHERE s.Photo IS NOT NULL;

INSERT INTO [StoolFecalysisReports] ([LabReportId], [Color], [Consistency], [Result])
SELECT m.NewId, s.[Color], s.[Consistency], s.[Result]
FROM [$(Legacy)].dbo.[StoolFecalyses] s JOIN #map m ON m.LegacyId = s.Id;

-- Urinalyses -> LabReports (Urinalysis) + UrinalysisReports
TRUNCATE TABLE #map;
MERGE [LabReports] AS t
USING (
    SELECT s.Id AS LegacyId,
           COALESCE(s.PatientId, r.PatientId) AS PatientId,
           r.Id AS PatientRegistrationId,
           s.PatientCode,
           s.PatientName,
           s.Age,
           s.Sex,
           s.CompanyOrPhysician,
           COALESCE(CAST(CAST(s.DateRequested AS datetime2(3)) AT TIME ZONE '$(LegacyTimeZone)' AT TIME ZONE 'UTC' AS datetime2(3)), CAST(CAST(s.CreatedDate AS datetime2(3)) AT TIME ZONE '$(LegacyTimeZone)' AT TIME ZONE 'UTC' AS datetime2(3))) AS DateRequested,
           s.Remarks,
           s.MedicalTechnologist,
           s.Pathologist,
           CAST(CAST(s.CreatedDate AS datetime2(3)) AT TIME ZONE '$(LegacyTimeZone)' AT TIME ZONE 'UTC' AS datetime2(3)) AS CreatedAtUtc,
           (SELECT u.Id FROM #u u WHERE u.Id = s.CreatedByUserId) AS CreatedByUserId,
           CAST(CAST(s.UpdatedDate AS datetime2(3)) AT TIME ZONE '$(LegacyTimeZone)' AT TIME ZONE 'UTC' AS datetime2(3)) AS UpdatedAtUtc,
           (SELECT u.Id FROM #u u WHERE u.Id = s.UpdatedByUserId) AS UpdatedByUserId,
           CASE WHEN s.IsActive = 1 THEN 0 ELSE 1 END AS IsDeleted,
           CASE WHEN s.IsActive = 0 THEN CAST(CAST(s.UpdatedDate AS datetime2(3)) AT TIME ZONE '$(LegacyTimeZone)' AT TIME ZONE 'UTC' AS datetime2(3)) END AS DeletedAtUtc,
           CASE WHEN s.IsActive = 0 THEN (SELECT u.Id FROM #u u WHERE u.Id = s.UpdatedByUserId) END AS DeletedByUserId
    FROM [$(Legacy)].dbo.[Urinalyses] s
    LEFT JOIN [$(Legacy)].dbo.[PatientRegistrations] r ON r.Id = s.PatientRegistrationId
    JOIN [$(Legacy)].dbo.[Patients] p ON p.Id = COALESCE(s.PatientId, r.PatientId)
) AS src ON 1 = 0
WHEN NOT MATCHED THEN INSERT ([ReportType], [PatientId], [PatientRegistrationId], [PatientCode], [PatientName], [Age], [Sex], [CompanyOrPhysician], [DateRequested], [Remarks], [MedicalTechnologist], [Pathologist], [CreatedAtUtc], [CreatedByUserId], [UpdatedAtUtc], [UpdatedByUserId], [IsDeleted], [DeletedAtUtc], [DeletedByUserId])
    VALUES ('Urinalysis', src.PatientId, src.PatientRegistrationId, src.PatientCode, src.PatientName, src.Age, src.Sex, src.CompanyOrPhysician, src.DateRequested, src.Remarks, src.MedicalTechnologist, src.Pathologist, src.CreatedAtUtc, src.CreatedByUserId, src.UpdatedAtUtc, src.UpdatedByUserId, src.IsDeleted, src.DeletedAtUtc, src.DeletedByUserId)
OUTPUT src.LegacyId, inserted.Id INTO #map (LegacyId, NewId);

INSERT INTO #skipped SELECT 'Urinalyses', s.Id, 'No matching patient for this lab row' FROM [$(Legacy)].dbo.[Urinalyses] s WHERE s.Id NOT IN (SELECT LegacyId FROM #map);

INSERT INTO [LabReportPhotos] ([LabReportId], [Content]) SELECT m.NewId, s.Photo FROM [$(Legacy)].dbo.[Urinalyses] s JOIN #map m ON m.LegacyId = s.Id WHERE s.Photo IS NOT NULL;

INSERT INTO [UrinalysisReports] ([LabReportId], [Color], [Appearance], [Reaction], [SPGravity], [Albumin], [Sugar], [PusCells], [RedCells], [MucusThreads], [EpithelialCells], [AmorphousUratesPO4], [Bacteria], [Casts], [Crystals], [Others])
SELECT m.NewId, s.[Color], s.[Appearance], s.[Reaction], s.[SPGravity], s.[Albumin], s.[Sugar], s.[PusCells], s.[RedCells], s.[MucusThreads], s.[EpithelialCells], s.[AmorphousUratesPO4], s.[Bacteria], s.[Casts], s.[Crystals], s.[Others]
FROM [$(Legacy)].dbo.[Urinalyses] s JOIN #map m ON m.LegacyId = s.Id;

-- Hematologies -> LabReports (Hematology) + HematologyReports
TRUNCATE TABLE #map;
MERGE [LabReports] AS t
USING (
    SELECT s.Id AS LegacyId,
           COALESCE(s.PatientId, r.PatientId) AS PatientId,
           r.Id AS PatientRegistrationId,
           s.PatientCode,
           s.PatientName,
           s.Age,
           s.Sex,
           s.CompanyOrPhysician,
           COALESCE(CAST(CAST(s.DateRequested AS datetime2(3)) AT TIME ZONE '$(LegacyTimeZone)' AT TIME ZONE 'UTC' AS datetime2(3)), CAST(CAST(s.CreatedDate AS datetime2(3)) AT TIME ZONE '$(LegacyTimeZone)' AT TIME ZONE 'UTC' AS datetime2(3))) AS DateRequested,
           s.Remarks,
           s.MedicalTechnologist,
           s.Pathologist,
           CAST(CAST(s.CreatedDate AS datetime2(3)) AT TIME ZONE '$(LegacyTimeZone)' AT TIME ZONE 'UTC' AS datetime2(3)) AS CreatedAtUtc,
           (SELECT u.Id FROM #u u WHERE u.Id = s.CreatedByUserId) AS CreatedByUserId,
           CAST(CAST(s.UpdatedDate AS datetime2(3)) AT TIME ZONE '$(LegacyTimeZone)' AT TIME ZONE 'UTC' AS datetime2(3)) AS UpdatedAtUtc,
           (SELECT u.Id FROM #u u WHERE u.Id = s.UpdatedByUserId) AS UpdatedByUserId,
           CASE WHEN s.IsActive = 1 THEN 0 ELSE 1 END AS IsDeleted,
           CASE WHEN s.IsActive = 0 THEN CAST(CAST(s.UpdatedDate AS datetime2(3)) AT TIME ZONE '$(LegacyTimeZone)' AT TIME ZONE 'UTC' AS datetime2(3)) END AS DeletedAtUtc,
           CASE WHEN s.IsActive = 0 THEN (SELECT u.Id FROM #u u WHERE u.Id = s.UpdatedByUserId) END AS DeletedByUserId
    FROM [$(Legacy)].dbo.[Hematologies] s
    LEFT JOIN [$(Legacy)].dbo.[PatientRegistrations] r ON r.Id = s.PatientRegistrationId
    JOIN [$(Legacy)].dbo.[Patients] p ON p.Id = COALESCE(s.PatientId, r.PatientId)
) AS src ON 1 = 0
WHEN NOT MATCHED THEN INSERT ([ReportType], [PatientId], [PatientRegistrationId], [PatientCode], [PatientName], [Age], [Sex], [CompanyOrPhysician], [DateRequested], [Remarks], [MedicalTechnologist], [Pathologist], [CreatedAtUtc], [CreatedByUserId], [UpdatedAtUtc], [UpdatedByUserId], [IsDeleted], [DeletedAtUtc], [DeletedByUserId])
    VALUES ('Hematology', src.PatientId, src.PatientRegistrationId, src.PatientCode, src.PatientName, src.Age, src.Sex, src.CompanyOrPhysician, src.DateRequested, src.Remarks, src.MedicalTechnologist, src.Pathologist, src.CreatedAtUtc, src.CreatedByUserId, src.UpdatedAtUtc, src.UpdatedByUserId, src.IsDeleted, src.DeletedAtUtc, src.DeletedByUserId)
OUTPUT src.LegacyId, inserted.Id INTO #map (LegacyId, NewId);

INSERT INTO #skipped SELECT 'Hematologies', s.Id, 'No matching patient for this lab row' FROM [$(Legacy)].dbo.[Hematologies] s WHERE s.Id NOT IN (SELECT LegacyId FROM #map);

INSERT INTO [LabReportPhotos] ([LabReportId], [Content]) SELECT m.NewId, s.Photo FROM [$(Legacy)].dbo.[Hematologies] s JOIN #map m ON m.LegacyId = s.Id WHERE s.Photo IS NOT NULL;

INSERT INTO [HematologyReports] ([LabReportId], [HematocritNValue], [HematocritResult], [HemoglobinNValue], [HemoglobinResult], [WBCCountNValue], [WBCCountResult], [SegmentersNValue], [SegmentersResult], [LymphocytesNValue], [LymphocytesResult], [EosinophilsNValue], [EosinophilsResult], [MonocytesNValue], [MonocytesResult], [BasophilsNValue], [BasophilsResult], [StabNValue], [StabResult], [PlateletCountNValue], [PlateletCountResult])
SELECT m.NewId, s.[HematocritNValue], s.[HematocritResult], s.[HemoglobinNValue], s.[HemoglobinResult], s.[WBCCountNValue], s.[WBCCountResult], s.[SegmentersNValue], s.[SegmentersResult], s.[LymphocytesNValue], s.[LymphocytesResult], s.[EosinophilsNValue], s.[EosinophilsResult], s.[MonocytesNValue], s.[MonocytesResult], s.[BasophilsNValue], s.[BasophilsResult], s.[StabNValue], s.[StabResult], s.[PlateletCountNValue], s.[PlateletCountResult]
FROM [$(Legacy)].dbo.[Hematologies] s JOIN #map m ON m.LegacyId = s.Id;

-- Immunologies -> LabReports (Immunology) + ImmunologyReports
TRUNCATE TABLE #map;
MERGE [LabReports] AS t
USING (
    SELECT s.Id AS LegacyId,
           COALESCE(s.PatientId, r.PatientId) AS PatientId,
           r.Id AS PatientRegistrationId,
           s.PatientCode,
           s.PatientName,
           s.Age,
           s.Sex,
           s.CompanyOrPhysician,
           COALESCE(CAST(CAST(s.DateRequested AS datetime2(3)) AT TIME ZONE '$(LegacyTimeZone)' AT TIME ZONE 'UTC' AS datetime2(3)), CAST(CAST(s.CreatedDate AS datetime2(3)) AT TIME ZONE '$(LegacyTimeZone)' AT TIME ZONE 'UTC' AS datetime2(3))) AS DateRequested,
           s.Remarks,
           s.MedicalTechnologist,
           s.Pathologist,
           CAST(CAST(s.CreatedDate AS datetime2(3)) AT TIME ZONE '$(LegacyTimeZone)' AT TIME ZONE 'UTC' AS datetime2(3)) AS CreatedAtUtc,
           (SELECT u.Id FROM #u u WHERE u.Id = s.CreatedByUserId) AS CreatedByUserId,
           CAST(CAST(s.UpdatedDate AS datetime2(3)) AT TIME ZONE '$(LegacyTimeZone)' AT TIME ZONE 'UTC' AS datetime2(3)) AS UpdatedAtUtc,
           (SELECT u.Id FROM #u u WHERE u.Id = s.UpdatedByUserId) AS UpdatedByUserId,
           CASE WHEN s.IsActive = 1 THEN 0 ELSE 1 END AS IsDeleted,
           CASE WHEN s.IsActive = 0 THEN CAST(CAST(s.UpdatedDate AS datetime2(3)) AT TIME ZONE '$(LegacyTimeZone)' AT TIME ZONE 'UTC' AS datetime2(3)) END AS DeletedAtUtc,
           CASE WHEN s.IsActive = 0 THEN (SELECT u.Id FROM #u u WHERE u.Id = s.UpdatedByUserId) END AS DeletedByUserId
    FROM [$(Legacy)].dbo.[Immunologies] s
    LEFT JOIN [$(Legacy)].dbo.[PatientRegistrations] r ON r.Id = s.PatientRegistrationId
    JOIN [$(Legacy)].dbo.[Patients] p ON p.Id = COALESCE(s.PatientId, r.PatientId)
) AS src ON 1 = 0
WHEN NOT MATCHED THEN INSERT ([ReportType], [PatientId], [PatientRegistrationId], [PatientCode], [PatientName], [Age], [Sex], [CompanyOrPhysician], [DateRequested], [Remarks], [MedicalTechnologist], [Pathologist], [CreatedAtUtc], [CreatedByUserId], [UpdatedAtUtc], [UpdatedByUserId], [IsDeleted], [DeletedAtUtc], [DeletedByUserId])
    VALUES ('Immunology', src.PatientId, src.PatientRegistrationId, src.PatientCode, src.PatientName, src.Age, src.Sex, src.CompanyOrPhysician, src.DateRequested, src.Remarks, src.MedicalTechnologist, src.Pathologist, src.CreatedAtUtc, src.CreatedByUserId, src.UpdatedAtUtc, src.UpdatedByUserId, src.IsDeleted, src.DeletedAtUtc, src.DeletedByUserId)
OUTPUT src.LegacyId, inserted.Id INTO #map (LegacyId, NewId);

INSERT INTO #skipped SELECT 'Immunologies', s.Id, 'No matching patient for this lab row' FROM [$(Legacy)].dbo.[Immunologies] s WHERE s.Id NOT IN (SELECT LegacyId FROM #map);

INSERT INTO [LabReportPhotos] ([LabReportId], [Content]) SELECT m.NewId, s.Photo FROM [$(Legacy)].dbo.[Immunologies] s JOIN #map m ON m.LegacyId = s.Id WHERE s.Photo IS NOT NULL;

INSERT INTO [ImmunologyReports] ([LabReportId], [Test], [Result])
SELECT m.NewId, s.[Test], s.[Result]
FROM [$(Legacy)].dbo.[Immunologies] s JOIN #map m ON m.LegacyId = s.Id;

-- Serologies -> LabReports (Serology) + SerologyReports
TRUNCATE TABLE #map;
MERGE [LabReports] AS t
USING (
    SELECT s.Id AS LegacyId,
           COALESCE(s.PatientId, r.PatientId) AS PatientId,
           r.Id AS PatientRegistrationId,
           s.PatientCode,
           s.PatientName,
           s.Age,
           s.Sex,
           s.CompanyOrPhysician,
           COALESCE(CAST(CAST(s.DateRequested AS datetime2(3)) AT TIME ZONE '$(LegacyTimeZone)' AT TIME ZONE 'UTC' AS datetime2(3)), CAST(CAST(s.CreatedDate AS datetime2(3)) AT TIME ZONE '$(LegacyTimeZone)' AT TIME ZONE 'UTC' AS datetime2(3))) AS DateRequested,
           s.Remarks,
           s.MedicalTechnologist,
           s.Pathologist,
           CAST(CAST(s.CreatedDate AS datetime2(3)) AT TIME ZONE '$(LegacyTimeZone)' AT TIME ZONE 'UTC' AS datetime2(3)) AS CreatedAtUtc,
           (SELECT u.Id FROM #u u WHERE u.Id = s.CreatedByUserId) AS CreatedByUserId,
           CAST(CAST(s.UpdatedDate AS datetime2(3)) AT TIME ZONE '$(LegacyTimeZone)' AT TIME ZONE 'UTC' AS datetime2(3)) AS UpdatedAtUtc,
           (SELECT u.Id FROM #u u WHERE u.Id = s.UpdatedByUserId) AS UpdatedByUserId,
           CASE WHEN s.IsActive = 1 THEN 0 ELSE 1 END AS IsDeleted,
           CASE WHEN s.IsActive = 0 THEN CAST(CAST(s.UpdatedDate AS datetime2(3)) AT TIME ZONE '$(LegacyTimeZone)' AT TIME ZONE 'UTC' AS datetime2(3)) END AS DeletedAtUtc,
           CASE WHEN s.IsActive = 0 THEN (SELECT u.Id FROM #u u WHERE u.Id = s.UpdatedByUserId) END AS DeletedByUserId
    FROM [$(Legacy)].dbo.[Serologies] s
    LEFT JOIN [$(Legacy)].dbo.[PatientRegistrations] r ON r.Id = s.PatientRegistrationId
    JOIN [$(Legacy)].dbo.[Patients] p ON p.Id = COALESCE(s.PatientId, r.PatientId)
) AS src ON 1 = 0
WHEN NOT MATCHED THEN INSERT ([ReportType], [PatientId], [PatientRegistrationId], [PatientCode], [PatientName], [Age], [Sex], [CompanyOrPhysician], [DateRequested], [Remarks], [MedicalTechnologist], [Pathologist], [CreatedAtUtc], [CreatedByUserId], [UpdatedAtUtc], [UpdatedByUserId], [IsDeleted], [DeletedAtUtc], [DeletedByUserId])
    VALUES ('Serology', src.PatientId, src.PatientRegistrationId, src.PatientCode, src.PatientName, src.Age, src.Sex, src.CompanyOrPhysician, src.DateRequested, src.Remarks, src.MedicalTechnologist, src.Pathologist, src.CreatedAtUtc, src.CreatedByUserId, src.UpdatedAtUtc, src.UpdatedByUserId, src.IsDeleted, src.DeletedAtUtc, src.DeletedByUserId)
OUTPUT src.LegacyId, inserted.Id INTO #map (LegacyId, NewId);

INSERT INTO #skipped SELECT 'Serologies', s.Id, 'No matching patient for this lab row' FROM [$(Legacy)].dbo.[Serologies] s WHERE s.Id NOT IN (SELECT LegacyId FROM #map);

INSERT INTO [LabReportPhotos] ([LabReportId], [Content]) SELECT m.NewId, s.Photo FROM [$(Legacy)].dbo.[Serologies] s JOIN #map m ON m.LegacyId = s.Id WHERE s.Photo IS NOT NULL;

INSERT INTO [SerologyReports] ([LabReportId], [Test], [Result])
SELECT m.NewId, s.[Test], s.[Result]
FROM [$(Legacy)].dbo.[Serologies] s JOIN #map m ON m.LegacyId = s.Id;

-- PregnancyTests -> LabReports (PregnancyTest) + PregnancyTestReports
TRUNCATE TABLE #map;
MERGE [LabReports] AS t
USING (
    SELECT s.Id AS LegacyId,
           COALESCE(s.PatientId, r.PatientId) AS PatientId,
           r.Id AS PatientRegistrationId,
           s.PatientCode,
           s.PatientName,
           s.Age,
           s.Sex,
           s.CompanyOrPhysician,
           COALESCE(CAST(CAST(s.DateRequested AS datetime2(3)) AT TIME ZONE '$(LegacyTimeZone)' AT TIME ZONE 'UTC' AS datetime2(3)), CAST(CAST(s.CreatedDate AS datetime2(3)) AT TIME ZONE '$(LegacyTimeZone)' AT TIME ZONE 'UTC' AS datetime2(3))) AS DateRequested,
           s.Remarks,
           s.MedicalTechnologist,
           s.Pathologist,
           CAST(CAST(s.CreatedDate AS datetime2(3)) AT TIME ZONE '$(LegacyTimeZone)' AT TIME ZONE 'UTC' AS datetime2(3)) AS CreatedAtUtc,
           (SELECT u.Id FROM #u u WHERE u.Id = s.CreatedByUserId) AS CreatedByUserId,
           CAST(CAST(s.UpdatedDate AS datetime2(3)) AT TIME ZONE '$(LegacyTimeZone)' AT TIME ZONE 'UTC' AS datetime2(3)) AS UpdatedAtUtc,
           (SELECT u.Id FROM #u u WHERE u.Id = s.UpdatedByUserId) AS UpdatedByUserId,
           CASE WHEN s.IsActive = 1 THEN 0 ELSE 1 END AS IsDeleted,
           CASE WHEN s.IsActive = 0 THEN CAST(CAST(s.UpdatedDate AS datetime2(3)) AT TIME ZONE '$(LegacyTimeZone)' AT TIME ZONE 'UTC' AS datetime2(3)) END AS DeletedAtUtc,
           CASE WHEN s.IsActive = 0 THEN (SELECT u.Id FROM #u u WHERE u.Id = s.UpdatedByUserId) END AS DeletedByUserId
    FROM [$(Legacy)].dbo.[PregnancyTests] s
    LEFT JOIN [$(Legacy)].dbo.[PatientRegistrations] r ON r.Id = s.PatientRegistrationId
    JOIN [$(Legacy)].dbo.[Patients] p ON p.Id = COALESCE(s.PatientId, r.PatientId)
) AS src ON 1 = 0
WHEN NOT MATCHED THEN INSERT ([ReportType], [PatientId], [PatientRegistrationId], [PatientCode], [PatientName], [Age], [Sex], [CompanyOrPhysician], [DateRequested], [Remarks], [MedicalTechnologist], [Pathologist], [CreatedAtUtc], [CreatedByUserId], [UpdatedAtUtc], [UpdatedByUserId], [IsDeleted], [DeletedAtUtc], [DeletedByUserId])
    VALUES ('PregnancyTest', src.PatientId, src.PatientRegistrationId, src.PatientCode, src.PatientName, src.Age, src.Sex, src.CompanyOrPhysician, src.DateRequested, src.Remarks, src.MedicalTechnologist, src.Pathologist, src.CreatedAtUtc, src.CreatedByUserId, src.UpdatedAtUtc, src.UpdatedByUserId, src.IsDeleted, src.DeletedAtUtc, src.DeletedByUserId)
OUTPUT src.LegacyId, inserted.Id INTO #map (LegacyId, NewId);

INSERT INTO #skipped SELECT 'PregnancyTests', s.Id, 'No matching patient for this lab row' FROM [$(Legacy)].dbo.[PregnancyTests] s WHERE s.Id NOT IN (SELECT LegacyId FROM #map);

INSERT INTO [LabReportPhotos] ([LabReportId], [Content]) SELECT m.NewId, s.Photo FROM [$(Legacy)].dbo.[PregnancyTests] s JOIN #map m ON m.LegacyId = s.Id WHERE s.Photo IS NOT NULL;

INSERT INTO [PregnancyTestReports] ([LabReportId], [Result])
SELECT m.NewId, s.[Result]
FROM [$(Legacy)].dbo.[PregnancyTests] s JOIN #map m ON m.LegacyId = s.Id;

-- ClinicalChemistries -> LabReports (ClinicalChemistry) + ClinicalChemistryReports
TRUNCATE TABLE #map;
MERGE [LabReports] AS t
USING (
    SELECT s.Id AS LegacyId,
           COALESCE(s.PatientId, r.PatientId) AS PatientId,
           r.Id AS PatientRegistrationId,
           s.PatientCode,
           s.PatientName,
           s.Age,
           s.Sex,
           s.CompanyOrPhysician,
           COALESCE(CAST(CAST(s.DateRequested AS datetime2(3)) AT TIME ZONE '$(LegacyTimeZone)' AT TIME ZONE 'UTC' AS datetime2(3)), CAST(CAST(s.CreatedDate AS datetime2(3)) AT TIME ZONE '$(LegacyTimeZone)' AT TIME ZONE 'UTC' AS datetime2(3))) AS DateRequested,
           CAST(NULL AS nvarchar(500)) AS Remarks,
           s.MedicalTechnologist,
           s.Pathologist,
           CAST(CAST(s.CreatedDate AS datetime2(3)) AT TIME ZONE '$(LegacyTimeZone)' AT TIME ZONE 'UTC' AS datetime2(3)) AS CreatedAtUtc,
           (SELECT u.Id FROM #u u WHERE u.Id = s.CreatedByUserId) AS CreatedByUserId,
           CAST(CAST(s.UpdatedDate AS datetime2(3)) AT TIME ZONE '$(LegacyTimeZone)' AT TIME ZONE 'UTC' AS datetime2(3)) AS UpdatedAtUtc,
           (SELECT u.Id FROM #u u WHERE u.Id = s.UpdatedByUserId) AS UpdatedByUserId,
           CASE WHEN s.IsActive = 1 THEN 0 ELSE 1 END AS IsDeleted,
           CASE WHEN s.IsActive = 0 THEN CAST(CAST(s.UpdatedDate AS datetime2(3)) AT TIME ZONE '$(LegacyTimeZone)' AT TIME ZONE 'UTC' AS datetime2(3)) END AS DeletedAtUtc,
           CASE WHEN s.IsActive = 0 THEN (SELECT u.Id FROM #u u WHERE u.Id = s.UpdatedByUserId) END AS DeletedByUserId
    FROM [$(Legacy)].dbo.[ClinicalChemistries] s
    LEFT JOIN [$(Legacy)].dbo.[PatientRegistrations] r ON r.Id = s.PatientRegistrationId
    JOIN [$(Legacy)].dbo.[Patients] p ON p.Id = COALESCE(s.PatientId, r.PatientId)
) AS src ON 1 = 0
WHEN NOT MATCHED THEN INSERT ([ReportType], [PatientId], [PatientRegistrationId], [PatientCode], [PatientName], [Age], [Sex], [CompanyOrPhysician], [DateRequested], [Remarks], [MedicalTechnologist], [Pathologist], [CreatedAtUtc], [CreatedByUserId], [UpdatedAtUtc], [UpdatedByUserId], [IsDeleted], [DeletedAtUtc], [DeletedByUserId])
    VALUES ('ClinicalChemistry', src.PatientId, src.PatientRegistrationId, src.PatientCode, src.PatientName, src.Age, src.Sex, src.CompanyOrPhysician, src.DateRequested, src.Remarks, src.MedicalTechnologist, src.Pathologist, src.CreatedAtUtc, src.CreatedByUserId, src.UpdatedAtUtc, src.UpdatedByUserId, src.IsDeleted, src.DeletedAtUtc, src.DeletedByUserId)
OUTPUT src.LegacyId, inserted.Id INTO #map (LegacyId, NewId);

INSERT INTO #skipped SELECT 'ClinicalChemistries', s.Id, 'No matching patient for this lab row' FROM [$(Legacy)].dbo.[ClinicalChemistries] s WHERE s.Id NOT IN (SELECT LegacyId FROM #map);

INSERT INTO [LabReportPhotos] ([LabReportId], [Content]) SELECT m.NewId, s.Photo FROM [$(Legacy)].dbo.[ClinicalChemistries] s JOIN #map m ON m.LegacyId = s.Id WHERE s.Photo IS NOT NULL;

INSERT INTO [ClinicalChemistryReports] ([LabReportId], [FBSNValue], [FBSResult], [TotalCholesterolNValue], [TotalCholesterolResult], [TriglyceridesNValue], [TriglyceridesResult], [HDLNValue], [HDLResult], [BUNNValue], [BUNResult], [CreatinineNValue], [CreatinineResult], [BloodUricAcidNValue], [BloodUricAcidResult], [LDLNValue], [LDLResult], [SGPTNValue], [SGPTResult])
SELECT m.NewId, s.[FBSNValue], s.[FBSResult], s.[TotalCholesterolNValue], s.[TotalCholesterolResult], s.[TriglyceridesNValue], s.[TriglyceridesResult], s.[HDLNValue], s.[HDLResult], s.[BUNNValue], s.[BUNResult], s.[CreatinineNValue], s.[CreatinineResult], s.[BloodUricAcidNValue], s.[BloodUricAcidResult], s.[LDLNValue], s.[LDLResult], s.[SGPTNValue], s.[SGPTResult]
FROM [$(Legacy)].dbo.[ClinicalChemistries] s JOIN #map m ON m.LegacyId = s.Id;

-- ClinicalChemistries1 -> LabReports (ClinicalChemistry1) + ClinicalChemistry1Reports
TRUNCATE TABLE #map;
MERGE [LabReports] AS t
USING (
    SELECT s.Id AS LegacyId,
           COALESCE(s.PatientId, r.PatientId) AS PatientId,
           r.Id AS PatientRegistrationId,
           s.PatientCode,
           s.PatientName,
           s.Age,
           s.Sex,
           s.CompanyOrPhysician,
           COALESCE(CAST(CAST(s.DateRequested AS datetime2(3)) AT TIME ZONE '$(LegacyTimeZone)' AT TIME ZONE 'UTC' AS datetime2(3)), CAST(CAST(s.CreatedDate AS datetime2(3)) AT TIME ZONE '$(LegacyTimeZone)' AT TIME ZONE 'UTC' AS datetime2(3))) AS DateRequested,
           s.Remarks,
           s.MedicalTechnologist,
           s.Pathologist,
           CAST(CAST(s.CreatedDate AS datetime2(3)) AT TIME ZONE '$(LegacyTimeZone)' AT TIME ZONE 'UTC' AS datetime2(3)) AS CreatedAtUtc,
           (SELECT u.Id FROM #u u WHERE u.Id = s.CreatedByUserId) AS CreatedByUserId,
           CAST(CAST(s.UpdatedDate AS datetime2(3)) AT TIME ZONE '$(LegacyTimeZone)' AT TIME ZONE 'UTC' AS datetime2(3)) AS UpdatedAtUtc,
           (SELECT u.Id FROM #u u WHERE u.Id = s.UpdatedByUserId) AS UpdatedByUserId,
           CASE WHEN s.IsActive = 1 THEN 0 ELSE 1 END AS IsDeleted,
           CASE WHEN s.IsActive = 0 THEN CAST(CAST(s.UpdatedDate AS datetime2(3)) AT TIME ZONE '$(LegacyTimeZone)' AT TIME ZONE 'UTC' AS datetime2(3)) END AS DeletedAtUtc,
           CASE WHEN s.IsActive = 0 THEN (SELECT u.Id FROM #u u WHERE u.Id = s.UpdatedByUserId) END AS DeletedByUserId
    FROM [$(Legacy)].dbo.[ClinicalChemistries1] s
    LEFT JOIN [$(Legacy)].dbo.[PatientRegistrations] r ON r.Id = s.PatientRegistrationId
    JOIN [$(Legacy)].dbo.[Patients] p ON p.Id = COALESCE(s.PatientId, r.PatientId)
) AS src ON 1 = 0
WHEN NOT MATCHED THEN INSERT ([ReportType], [PatientId], [PatientRegistrationId], [PatientCode], [PatientName], [Age], [Sex], [CompanyOrPhysician], [DateRequested], [Remarks], [MedicalTechnologist], [Pathologist], [CreatedAtUtc], [CreatedByUserId], [UpdatedAtUtc], [UpdatedByUserId], [IsDeleted], [DeletedAtUtc], [DeletedByUserId])
    VALUES ('ClinicalChemistry1', src.PatientId, src.PatientRegistrationId, src.PatientCode, src.PatientName, src.Age, src.Sex, src.CompanyOrPhysician, src.DateRequested, src.Remarks, src.MedicalTechnologist, src.Pathologist, src.CreatedAtUtc, src.CreatedByUserId, src.UpdatedAtUtc, src.UpdatedByUserId, src.IsDeleted, src.DeletedAtUtc, src.DeletedByUserId)
OUTPUT src.LegacyId, inserted.Id INTO #map (LegacyId, NewId);

INSERT INTO #skipped SELECT 'ClinicalChemistries1', s.Id, 'No matching patient for this lab row' FROM [$(Legacy)].dbo.[ClinicalChemistries1] s WHERE s.Id NOT IN (SELECT LegacyId FROM #map);

INSERT INTO [LabReportPhotos] ([LabReportId], [Content]) SELECT m.NewId, s.Photo FROM [$(Legacy)].dbo.[ClinicalChemistries1] s JOIN #map m ON m.LegacyId = s.Id WHERE s.Photo IS NOT NULL;

INSERT INTO [ClinicalChemistry1Reports] ([LabReportId], [Test], [Result])
SELECT m.NewId, s.[Test], s.[Result]
FROM [$(Legacy)].dbo.[ClinicalChemistries1] s JOIN #map m ON m.LegacyId = s.Id;

-- ClinicalChemistries2 -> LabReports (ClinicalChemistry2) + ClinicalChemistry2Reports
TRUNCATE TABLE #map;
MERGE [LabReports] AS t
USING (
    SELECT s.Id AS LegacyId,
           COALESCE(s.PatientId, r.PatientId) AS PatientId,
           r.Id AS PatientRegistrationId,
           s.PatientCode,
           s.PatientName,
           s.Age,
           s.Sex,
           s.CompanyOrPhysician,
           COALESCE(CAST(CAST(s.DateRequested AS datetime2(3)) AT TIME ZONE '$(LegacyTimeZone)' AT TIME ZONE 'UTC' AS datetime2(3)), CAST(CAST(s.CreatedDate AS datetime2(3)) AT TIME ZONE '$(LegacyTimeZone)' AT TIME ZONE 'UTC' AS datetime2(3))) AS DateRequested,
           CAST(NULL AS nvarchar(500)) AS Remarks,
           s.MedicalTechnologist,
           s.Pathologist,
           CAST(CAST(s.CreatedDate AS datetime2(3)) AT TIME ZONE '$(LegacyTimeZone)' AT TIME ZONE 'UTC' AS datetime2(3)) AS CreatedAtUtc,
           (SELECT u.Id FROM #u u WHERE u.Id = s.CreatedByUserId) AS CreatedByUserId,
           CAST(CAST(s.UpdatedDate AS datetime2(3)) AT TIME ZONE '$(LegacyTimeZone)' AT TIME ZONE 'UTC' AS datetime2(3)) AS UpdatedAtUtc,
           (SELECT u.Id FROM #u u WHERE u.Id = s.UpdatedByUserId) AS UpdatedByUserId,
           CASE WHEN s.IsActive = 1 THEN 0 ELSE 1 END AS IsDeleted,
           CASE WHEN s.IsActive = 0 THEN CAST(CAST(s.UpdatedDate AS datetime2(3)) AT TIME ZONE '$(LegacyTimeZone)' AT TIME ZONE 'UTC' AS datetime2(3)) END AS DeletedAtUtc,
           CASE WHEN s.IsActive = 0 THEN (SELECT u.Id FROM #u u WHERE u.Id = s.UpdatedByUserId) END AS DeletedByUserId
    FROM [$(Legacy)].dbo.[ClinicalChemistries2] s
    LEFT JOIN [$(Legacy)].dbo.[PatientRegistrations] r ON r.Id = s.PatientRegistrationId
    JOIN [$(Legacy)].dbo.[Patients] p ON p.Id = COALESCE(s.PatientId, r.PatientId)
) AS src ON 1 = 0
WHEN NOT MATCHED THEN INSERT ([ReportType], [PatientId], [PatientRegistrationId], [PatientCode], [PatientName], [Age], [Sex], [CompanyOrPhysician], [DateRequested], [Remarks], [MedicalTechnologist], [Pathologist], [CreatedAtUtc], [CreatedByUserId], [UpdatedAtUtc], [UpdatedByUserId], [IsDeleted], [DeletedAtUtc], [DeletedByUserId])
    VALUES ('ClinicalChemistry2', src.PatientId, src.PatientRegistrationId, src.PatientCode, src.PatientName, src.Age, src.Sex, src.CompanyOrPhysician, src.DateRequested, src.Remarks, src.MedicalTechnologist, src.Pathologist, src.CreatedAtUtc, src.CreatedByUserId, src.UpdatedAtUtc, src.UpdatedByUserId, src.IsDeleted, src.DeletedAtUtc, src.DeletedByUserId)
OUTPUT src.LegacyId, inserted.Id INTO #map (LegacyId, NewId);

INSERT INTO #skipped SELECT 'ClinicalChemistries2', s.Id, 'No matching patient for this lab row' FROM [$(Legacy)].dbo.[ClinicalChemistries2] s WHERE s.Id NOT IN (SELECT LegacyId FROM #map);

INSERT INTO [LabReportPhotos] ([LabReportId], [Content]) SELECT m.NewId, s.Photo FROM [$(Legacy)].dbo.[ClinicalChemistries2] s JOIN #map m ON m.LegacyId = s.Id WHERE s.Photo IS NOT NULL;

INSERT INTO [ClinicalChemistry2Reports] ([LabReportId], [AlkalinePhosphataseCNValue], [AlkalinePhosphataseCUnit], [AlkalinePhosphataseCResults], [AlkalinePhosphataseSNValue], [AlkalinePhosphataseSUnit], [AlkalinePhosphataseSResults], [SGOTCNValue], [SGOTCUnit], [SGOTCResults], [SGOTSNValue], [SGOTSUnit], [SGOTSResults])
SELECT m.NewId, s.[AlkalinePhosphataseCNValue], s.[AlkalinePhosphataseCUnit], s.[AlkalinePhosphataseCResults], s.[AlkalinePhosphataseSNValue], s.[AlkalinePhosphataseSUnit], s.[AlkalinePhosphataseSResults], s.[SGOTCNValue], s.[SGOTCUnit], s.[SGOTCResults], s.[SGOTSNValue], s.[SGOTSUnit], s.[SGOTSResults]
FROM [$(Legacy)].dbo.[ClinicalChemistries2] s JOIN #map m ON m.LegacyId = s.Id;

-- APEs -> LabReports (AnnualPhysicalExam) + AnnualPhysicalExamReports
TRUNCATE TABLE #map;
MERGE [LabReports] AS t
USING (
    SELECT s.Id AS LegacyId,
           COALESCE(s.PatientId, r.PatientId) AS PatientId,
           r.Id AS PatientRegistrationId,
           p.PatientCode,
           s.PatientName,
           s.Age,
           s.Gender AS Sex,
           s.CompanyName AS CompanyOrPhysician,
           COALESCE(CAST(CAST(s.DateInputted AS datetime2(3)) AT TIME ZONE '$(LegacyTimeZone)' AT TIME ZONE 'UTC' AS datetime2(3)), CAST(CAST(s.CreatedDate AS datetime2(3)) AT TIME ZONE '$(LegacyTimeZone)' AT TIME ZONE 'UTC' AS datetime2(3))) AS DateRequested,
           CAST(NULL AS nvarchar(500)) AS Remarks,
           CAST(NULL AS nvarchar(100)) AS MedicalTechnologist,
           CAST(NULL AS nvarchar(100)) AS Pathologist,
           CAST(CAST(s.CreatedDate AS datetime2(3)) AT TIME ZONE '$(LegacyTimeZone)' AT TIME ZONE 'UTC' AS datetime2(3)) AS CreatedAtUtc,
           (SELECT u.Id FROM #u u WHERE u.Id = s.CreatedByUserId) AS CreatedByUserId,
           CAST(CAST(s.UpdatedDate AS datetime2(3)) AT TIME ZONE '$(LegacyTimeZone)' AT TIME ZONE 'UTC' AS datetime2(3)) AS UpdatedAtUtc,
           (SELECT u.Id FROM #u u WHERE u.Id = s.UpdatedByUserId) AS UpdatedByUserId,
           CASE WHEN s.IsActive = 1 THEN 0 ELSE 1 END AS IsDeleted,
           CASE WHEN s.IsActive = 0 THEN CAST(CAST(s.UpdatedDate AS datetime2(3)) AT TIME ZONE '$(LegacyTimeZone)' AT TIME ZONE 'UTC' AS datetime2(3)) END AS DeletedAtUtc,
           CASE WHEN s.IsActive = 0 THEN (SELECT u.Id FROM #u u WHERE u.Id = s.UpdatedByUserId) END AS DeletedByUserId
    FROM [$(Legacy)].dbo.[APEs] s
    LEFT JOIN [$(Legacy)].dbo.[PatientRegistrations] r ON r.Id = s.PatientRegistrationId
    JOIN [$(Legacy)].dbo.[Patients] p ON p.Id = COALESCE(s.PatientId, r.PatientId)
) AS src ON 1 = 0
WHEN NOT MATCHED THEN INSERT ([ReportType], [PatientId], [PatientRegistrationId], [PatientCode], [PatientName], [Age], [Sex], [CompanyOrPhysician], [DateRequested], [Remarks], [MedicalTechnologist], [Pathologist], [CreatedAtUtc], [CreatedByUserId], [UpdatedAtUtc], [UpdatedByUserId], [IsDeleted], [DeletedAtUtc], [DeletedByUserId])
    VALUES ('AnnualPhysicalExam', src.PatientId, src.PatientRegistrationId, src.PatientCode, src.PatientName, src.Age, src.Sex, src.CompanyOrPhysician, src.DateRequested, src.Remarks, src.MedicalTechnologist, src.Pathologist, src.CreatedAtUtc, src.CreatedByUserId, src.UpdatedAtUtc, src.UpdatedByUserId, src.IsDeleted, src.DeletedAtUtc, src.DeletedByUserId)
OUTPUT src.LegacyId, inserted.Id INTO #map (LegacyId, NewId);

INSERT INTO #skipped SELECT 'APEs', s.Id, 'No matching patient for this lab row' FROM [$(Legacy)].dbo.[APEs] s WHERE s.Id NOT IN (SELECT LegacyId FROM #map);

INSERT INTO [AnnualPhysicalExamReports] ([LabReportId], [DepartmentOrAgency], [BirthDate], [CivilStatus], [ContactNo], [ENT], [Gastroenterology], [Respiratory], [IntegumentarySkin], [Cardiology], [Psychology], [Endocrinology], [OBGyneUrology], [Muscoloskeletal], [InfectiousCommunicable], [Neurological], [Surgical], [OthersPast], [Medications], [ReviewOfSystems], [Allergies], [IsSmoking], [SmokingSinceWhen], [NumberOfSticksPerDay], [IsDrinking], [DrinkingSinceWhen], [NumberOfBottles], [DrinkingFrequency], [LMP], [LMPType], [BP1st], [BP2nd], [CardiacRate1st], [CardiacRate2nd], [Height], [Weight], [BMICategory], [VARightEyeWGlasses], [VARightEyeWOGlasses], [VALeftEyeWGlasses], [VALeftEyeWOGlasses], [VisualAcuity], [Skin], [HeadScalp], [Eyes], [Ears], [Nose], [TeethTonsilsThroatPharynx], [NeckLymphNodesThyroid], [ThoraxBreast], [HeartLungs], [AbdomenLiverSpleen], [InguinalAreaGenitalsAnus], [ExtremetiesSpine], [Tattoo], [MassCyst], [OthersPE], [Findings], [VitalSignsBy], [HeightWeightBy])
SELECT m.NewId, s.[DepartmentOrAgency], s.[BirthDate], s.[CivilStatus], s.[ContactNo], s.[ENT], s.[Gastroenterology], s.[Respiratory], s.[IntegumentarySkin], s.[Cardiology], s.[Psychology], s.[Endocrinology], s.[OBGyneUrology], s.[Muscoloskeletal], s.[InfectiousCommunicable], s.[Neurological], s.[Surgical], s.[OthersPast], s.[Medications], s.[ReviewOfSystems], s.[Allergies], s.[IsSmoking], s.[SmokingSinceWhen], s.[NumberOfSticksPerDay], s.[IsDrinking], s.[DrinkingSinceWhen], s.[NumberOfBottles], s.[DrinkingFrequency], s.[LMP], s.[LMPType], s.[BP1st], s.[BP2nd], s.[CardiacRate1st], s.[CardiacRate2nd], s.[Height], s.[Weight], s.[BMICategory], s.[VARightEyeWGlasses], s.[VARightEyeWOGlasses], s.[VALeftEyeWGlasses], s.[VALeftEyeWOGlasses], s.[VisualAcuity], RTRIM(s.[Skin]), RTRIM(s.[HeadScalp]), RTRIM(s.[Eyes]), RTRIM(s.[Ears]), RTRIM(s.[Nose]), RTRIM(s.[TeethTonsilsThroatPharynx]), RTRIM(s.[NeckLymphNodesThyroid]), RTRIM(s.[ThoraxBreast]), RTRIM(s.[HeartLungs]), RTRIM(s.[AbdomenLiverSpleen]), RTRIM(s.[InguinalAreaGenitalsAnus]), RTRIM(s.[ExtremetiesSpine]), RTRIM(s.[Tattoo]), RTRIM(s.[MassCyst]), RTRIM(s.[OthersPE]), s.[Findings], s.[VitalSignsBy], s.[HeightWeightBy]
FROM [$(Legacy)].dbo.[APEs] s JOIN #map m ON m.LegacyId = s.Id;

-- MERs -> LabReports (MedicalExamination) + MedicalExaminationReports
TRUNCATE TABLE #map;
MERGE [LabReports] AS t
USING (
    SELECT s.Id AS LegacyId,
           COALESCE(s.PatientId, r.PatientId) AS PatientId,
           r.Id AS PatientRegistrationId,
           p.PatientCode,
           s.PatientName,
           s.Age,
           s.Gender AS Sex,
           s.CompanyName AS CompanyOrPhysician,
           COALESCE(CAST(CAST(s.DateInputted AS datetime2(3)) AT TIME ZONE '$(LegacyTimeZone)' AT TIME ZONE 'UTC' AS datetime2(3)), CAST(CAST(s.CreatedDate AS datetime2(3)) AT TIME ZONE '$(LegacyTimeZone)' AT TIME ZONE 'UTC' AS datetime2(3))) AS DateRequested,
           s.Remarks,
           CAST(NULL AS nvarchar(100)) AS MedicalTechnologist,
           CAST(NULL AS nvarchar(100)) AS Pathologist,
           CAST(CAST(s.CreatedDate AS datetime2(3)) AT TIME ZONE '$(LegacyTimeZone)' AT TIME ZONE 'UTC' AS datetime2(3)) AS CreatedAtUtc,
           (SELECT u.Id FROM #u u WHERE u.Id = s.CreatedByUserId) AS CreatedByUserId,
           CAST(CAST(s.UpdatedDate AS datetime2(3)) AT TIME ZONE '$(LegacyTimeZone)' AT TIME ZONE 'UTC' AS datetime2(3)) AS UpdatedAtUtc,
           (SELECT u.Id FROM #u u WHERE u.Id = s.UpdatedByUserId) AS UpdatedByUserId,
           CASE WHEN s.IsActive = 1 THEN 0 ELSE 1 END AS IsDeleted,
           CASE WHEN s.IsActive = 0 THEN CAST(CAST(s.UpdatedDate AS datetime2(3)) AT TIME ZONE '$(LegacyTimeZone)' AT TIME ZONE 'UTC' AS datetime2(3)) END AS DeletedAtUtc,
           CASE WHEN s.IsActive = 0 THEN (SELECT u.Id FROM #u u WHERE u.Id = s.UpdatedByUserId) END AS DeletedByUserId
    FROM [$(Legacy)].dbo.[MERs] s
    LEFT JOIN [$(Legacy)].dbo.[PatientRegistrations] r ON r.Id = s.PatientRegistrationId
    JOIN [$(Legacy)].dbo.[Patients] p ON p.Id = COALESCE(s.PatientId, r.PatientId)
) AS src ON 1 = 0
WHEN NOT MATCHED THEN INSERT ([ReportType], [PatientId], [PatientRegistrationId], [PatientCode], [PatientName], [Age], [Sex], [CompanyOrPhysician], [DateRequested], [Remarks], [MedicalTechnologist], [Pathologist], [CreatedAtUtc], [CreatedByUserId], [UpdatedAtUtc], [UpdatedByUserId], [IsDeleted], [DeletedAtUtc], [DeletedByUserId])
    VALUES ('MedicalExamination', src.PatientId, src.PatientRegistrationId, src.PatientCode, src.PatientName, src.Age, src.Sex, src.CompanyOrPhysician, src.DateRequested, src.Remarks, src.MedicalTechnologist, src.Pathologist, src.CreatedAtUtc, src.CreatedByUserId, src.UpdatedAtUtc, src.UpdatedByUserId, src.IsDeleted, src.DeletedAtUtc, src.DeletedByUserId)
OUTPUT src.LegacyId, inserted.Id INTO #map (LegacyId, NewId);

INSERT INTO #skipped SELECT 'MERs', s.Id, 'No matching patient for this lab row' FROM [$(Legacy)].dbo.[MERs] s WHERE s.Id NOT IN (SELECT LegacyId FROM #map);

INSERT INTO [MedicalExaminationReports] ([LabReportId], [ContactNo], [CivilStatus], [ChestXray], [ChestXrayRemarks], [CBC], [CBCRemarks], [Urinalysis], [UrinalysisRemarks], [Fecalysis], [FecalysisRemarks], [HBsAg], [HBsAgRemarks], [DrugTest2Panel], [DrugTest2PanelRemarks], [DrugTest4Panel], [DrugTest4PanelRemarks], [Classification], [MedicalSurgicalHistory], [Assessment], [AssessmentDoneBy], [PhysicianName], [PhysicianLicense])
SELECT m.NewId, s.[ContactNo], s.[CivilStatus], s.[ChestXray], s.[ChestXrayRemarks], s.[CBC], s.[CBCRemarks], s.[Urinalysis], s.[UrinalysisRemarks], s.[Fecalysis], s.[FecalysisRemarks], s.[HBsAg], s.[HBsAgRemarks], s.[DrugTest2Panel], s.[DrugTest2PanelRemarks], s.[DrugTest4Panel], s.[DrugTest4PanelRemarks], s.[Classification], s.[MedicalSurgicalHistory], s.[Assessment], s.[AssessmentDoneBy], s.[PhysicianName], s.[PhysicianLicense]
FROM [$(Legacy)].dbo.[MERs] s JOIN #map m ON m.LegacyId = s.Id;

-- ===== Summary =====
SELECT SourceTable AS SkippedSourceTable, LegacyId, Reason FROM #skipped ORDER BY SourceTable, LegacyId;

COMMIT TRANSACTION;
PRINT 'Migration committed. Run db/verify-migration.sql to compare row counts.';
