<#
.SYNOPSIS
  Generates db/migrate-from-legacy.sql and db/verify-migration.sql.

.DESCRIPTION
  The lab detail column lists are read from the legacy database catalog so the 150+ analyte columns
  are never retyped. Re-run this script if the legacy schema or the new model changes:

    pwsh tools/Generate-LegacyMigration.ps1 -Server 'DDDAVID\MSSQLSERVER01' -LegacyDatabase DiagnosticLabsDB

  Only reads from the legacy database.
#>
param(
    [string]$Server = 'localhost',
    [string]$LegacyDatabase = 'DiagnosticLabsDB'
)

$ErrorActionPreference = 'Stop'
$root = Split-Path $PSScriptRoot -Parent
$dollar = '$'

# ---------- helpers that emit T-SQL fragments ----------
function U([string]$col) {
    # legacy local time -> UTC datetime2(3)
    "CAST(CAST($col AS datetime2(3)) AT TIME ZONE '${dollar}(LegacyTimeZone)' AT TIME ZONE 'UTC' AS datetime2(3))"
}
function UserRef([string]$col) { "(SELECT u.Id FROM #u u WHERE u.Id = $col)" }

$legacy = "[${dollar}(Legacy)].dbo"

function AuditCols([string]$kind, [bool]$hasCreated = $true) {
    $created = if ($hasCreated) { 's.CreatedDate' } else { 's.UpdatedDate' }
    $createdBy = if ($hasCreated) { 's.CreatedByUserId' } else { 's.UpdatedByUserId' }
    $cols = [ordered]@{
        CreatedAtUtc    = (U $created)
        CreatedByUserId = (UserRef $createdBy)
        UpdatedAtUtc    = (U 's.UpdatedDate')
        UpdatedByUserId = (UserRef 's.UpdatedByUserId')
    }
    switch ($kind) {
        'ref'  { $cols['IsActive'] = 's.IsActive' }
        'soft' {
            $cols['IsDeleted'] = 'CASE WHEN s.IsActive = 1 THEN 0 ELSE 1 END'
            $cols['DeletedAtUtc'] = "CASE WHEN s.IsActive = 0 THEN $(U 's.UpdatedDate') END"
            $cols['DeletedByUserId'] = "CASE WHEN s.IsActive = 0 THEN $(UserRef 's.UpdatedByUserId') END"
        }
    }
    $cols
}

$out = New-Object System.Text.StringBuilder
$verify = New-Object System.Text.StringBuilder
function Emit([string]$text) { [void]$out.AppendLine($text) }

function InsertSpec {
    param([string]$Target, [string]$Source, $Cols, [string]$Kind = 'none', [bool]$Identity = $false, [string]$Where = '', [bool]$HasCreated = $true, [string]$SourceExpr = '')
    $all = [ordered]@{}
    foreach ($k in $Cols.Keys) { $all[$k] = $Cols[$k] }
    if ($Kind -ne 'none') { foreach ($k in (AuditCols $Kind $HasCreated).Keys) { $all[$k] = (AuditCols $Kind $HasCreated)[$k] } }
    $names = ($all.Keys | ForEach-Object { "[$_]" }) -join ', '
    $values = ($all.Keys | ForEach-Object { $all[$_] }) -join ",`r`n        "
    $from = if ($SourceExpr) { $SourceExpr } else { "$legacy.[$Source] s" }
    Emit "-- $Source -> $Target"
    if ($Identity) { Emit "SET IDENTITY_INSERT [$Target] ON;" }
    Emit "INSERT INTO [$Target] ($names)"
    Emit "SELECT $values"
    Emit "FROM $from"
    if ($Where) { Emit "WHERE $Where" }
    Emit ';'
    if ($Identity) { Emit "SET IDENTITY_INSERT [$Target] OFF;" }
    Emit ''
}

function Same([string[]]$names) { $d = [ordered]@{}; foreach ($n in $names) { $d[$n] = "s.[$n]" }; $d }
function WithId([string[]]$names) { Same (@('Id') + $names) }

# ---------- header ----------
Emit @"
/*
  One-time data migration: legacy DiagnosticLabsDB -> new schema.
  GENERATED by tools/Generate-LegacyMigration.ps1 - do not edit by hand.

  Run against an EMPTY, freshly migrated target database (the legacy database is only read):

    sqlcmd -S <server> -d <target> -E -C -I -b -i db/migrate-from-legacy.sql ^
           -v Legacy=DiagnosticLabsDB LegacyTimeZone="Singapore Standard Time"

  Notes
   * Legacy timestamps are local time; they are converted to UTC using `$(LegacyTimeZone) (a Windows time zone id).
   * Everything runs in one transaction; any error rolls the whole migration back.
   * Ids are preserved for every table except lab reports (merged into LabReports, new ids) and the
     WALK-IN company (legacy Id 0 is not allowed to stay 0).
   * Audit user ids that do not exist in Users (e.g. the legacy 0 placeholder) become NULL.
   * Lab rows from before the registration workflow (PatientRegistrationId = 0) keep their patient and get a NULL registration.
   * Lab rows whose patient cannot be found cannot satisfy the new foreign keys; they are skipped and listed at the end.
*/
SET NOCOUNT ON;
SET XACT_ABORT ON;

IF EXISTS (SELECT 1 FROM [Users]) OR EXISTS (SELECT 1 FROM [Patients]) OR EXISTS (SELECT 1 FROM [Modules])
    THROW 50000, 'Target database is not empty. Run this on a freshly migrated, empty database.', 1;

IF NOT EXISTS (SELECT 1 FROM sys.time_zone_info WHERE name = '${dollar}(LegacyTimeZone)')
    THROW 50001, 'LegacyTimeZone is not a valid Windows time zone id.', 1;

BEGIN TRANSACTION;

CREATE TABLE #u (Id bigint PRIMARY KEY);
INSERT INTO #u SELECT Id FROM $legacy.[Users];

CREATE TABLE #skipped (SourceTable sysname, LegacyId bigint, Reason nvarchar(200));
CREATE TABLE #map (LegacyId bigint PRIMARY KEY, NewId bigint NOT NULL);

"@

# ---------- users first: every audit column is a foreign key to Users ----------
$users = WithId @('Username', 'FullName')
$users['PasswordHash'] = 's.[Password]'
$users['IsAdmin'] = 's.IsAdmin'
$users['MustChangePassword'] = '0'
$users['FailedLoginCount'] = '0'
InsertSpec 'Users' 'Users' $users 'ref' $true

# ---------- identity / menu ----------
InsertSpec 'ModuleTypes' 'ModuleTypes' (WithId @('ModuleTypeName', 'Icon', 'SortOrder', 'IsActive', 'IsAdmin'))

# Modules reference Services, so Services come first
InsertSpec 'Services' 'Services' (WithId @('ServiceName', 'ServiceDescription', 'Price')) 'ref' $true
InsertSpec 'Modules' 'Modules' (WithId @('ModuleTypeId', 'ModuleName', 'HasView', 'HasCreate', 'HasEdit', 'HasDelete', 'HasSearch', 'HasPrint', 'HasShowList', 'HasSetDefaults', 'Icon', 'SortOrder', 'IsActive', 'ServiceId'))

$perm =WithId @('UserId', 'ModuleId')
foreach ($a in 'AllowCreate', 'AllowEdit', 'AllowDelete', 'AllowPrint') { $perm[$a] = "CASE WHEN s.ViewOnly = 1 THEN 0 ELSE s.[$a] END" }
# A legacy row existed for EVERY module per user (all flags off = no access). In the new model a row means access,
# so only rows that grant something are migrated: View Only becomes a row with no actions.
InsertSpec 'UserPermissions' 'UserPermissions' $perm 'audit' $true 's.ViewOnly = 1 OR s.AllowCreate = 1 OR s.AllowEdit = 1 OR s.AllowDelete = 1 OR s.AllowPrint = 1'

# ---------- reference data ----------
# The legacy WALK-IN row (Id 0) is not migrated: in the new app "no company" simply means no company (NULL).
InsertSpec 'Companies' 'Companies' (WithId @('CompanyName', 'Address', 'ContactNumbers', 'ContactPerson')) 'ref' $true 's.Id <> 0'

$setup = Same @('CompanyName', 'SubCompanyName', 'Tagline', 'Address', 'ContactNumbers', 'Email', 'Code', 'Logo')
$setup = [ordered]@{ Id = 's.Id' } + $setup
InsertSpec 'CompanySetups' 'CompanySetups' $setup 'audit' $true '' $false

InsertSpec 'Departments' 'Departments' (WithId @('DepartmentName', 'DepartmentDescription')) 'ref' $true
InsertSpec 'Items' 'Items' (WithId @('ItemName', 'Cost')) 'ref' $true
InsertSpec 'ItemLocations' 'ItemLocations' (WithId @('ItemLocationName')) 'ref' $true
InsertSpec 'ItemQuantities' 'ItemQuantities' (WithId @('ItemId', 'ItemLocationId', 'Quantity')) 'soft' $true
InsertSpec 'ServiceItemQuantities' 'ServiceItemQuantities' (WithId @('ServiceId', 'ItemId', 'Quantity')) 'soft' $true
InsertSpec 'Discounts' 'Discounts' (WithId @('DiscountName', 'DiscountDescription')) 'ref' $true
InsertSpec 'DiscountDetails' 'DiscountDetails' (WithId @('DiscountId', 'Amount', 'Percentage')) 'soft' $true

$pkg = WithId @('PackageName', 'PackageDescription', 'Price')
$pkg['CompanyId'] = 'NULLIF(s.CompanyId, 0)'
InsertSpec 'Packages' 'Packages' $pkg 'ref' $true
InsertSpec 'PackageServices' 'PackageServices' (WithId @('PackageId', 'ServiceId', 'Price')) 'soft' $true

# Lookup tables merged into LookupValues / ModuleDefaults (new ids)
$lk = [ordered]@{ ModuleId = 's.ModuleId'; Kind = '1'; FieldName = 's.FieldName'; Title = 's.FieldValueTitle'; Value = 's.FieldValue' }
InsertSpec 'LookupValues' 'DefaultValues' $lk 'ref'
$lk = [ordered]@{ ModuleId = 's.ModuleId'; Kind = '2'; FieldName = 's.FieldName'; Title = 'NULL'; Value = 's.FieldValue' }
InsertSpec 'LookupValues' 'SingleLineEntries' $lk 'ref'
$lk = [ordered]@{ ModuleId = 's.ModuleId'; Kind = '3'; FieldName = 's.FieldName'; Title = 's.FieldValueTitle'; Value = 's.FieldValue' }
InsertSpec 'LookupValues' 'MultiLineEntries' $lk 'ref'
InsertSpec 'ModuleDefaults' 'LabResultsDefaults' ([ordered]@{ ModuleId = 's.ModuleId'; Defaults = 's.Defaults' }) 'ref'

# ---------- patients, registrations, payments ----------
$pat = WithId @('PatientCode', 'PatientName')
$pat['DateOfBirth'] = 'CAST(s.DateOfBirth AS date)'
# the new model computes age from the birth date; the legacy text is only kept where there is no birth date
$pat['Age'] = "NULLIF(LTRIM(RTRIM(CASE WHEN s.DateOfBirth IS NULL THEN s.Age END)), '')"
$pat['Sex'] = 's.Gender'
$pat['CivilStatus'] = 's.CivilStatus'
$pat['Address'] = 's.Address'
$pat['ContactNumbers'] = 's.ContactNumbers'
InsertSpec 'Patients' 'Patients' $pat 'soft' $true

$reg = WithId @('RegistrationCode')
$reg['InputDate'] = (U 's.InputDate')
foreach ($c in 'PatientId') { $reg[$c] = "s.[$c]" }
$reg['CompanyId'] = 'NULLIF(s.CompanyId, 0)'
$reg['PackageId'] = 'NULLIF(s.PackageId, 0)'
foreach ($c in 'BatchName', 'AmountDue', 'DiscountAmount', 'DiscountPercentage', 'DiscountTotal') { $reg[$c] = "s.[$c]" }
InsertSpec 'PatientRegistrations' 'PatientRegistrations' $reg 'soft' $true
InsertSpec 'PatientRegistrationServices' 'PatientRegistrationServices' (WithId @('PatientRegistrationId', 'ServiceId', 'Price')) 'soft' $true

$pay = WithId @()
$pay['PaymentDate'] = (U 's.PaymentDate')
$pay['PatientRegistrationId'] = 's.PatientRegistrationId'
$pay['PaymentAmount'] = 's.PaymentAmount'
$pay['Type'] = 'CASE WHEN s.IsCharge = 1 THEN 1 ELSE 0 END'
InsertSpec 'Payments' 'Payments' $pay 'soft' $true

Emit @"
-- LatestCodeNumbers view -> CodeSequences (keeps the next registration number per prefix)
INSERT INTO [CodeSequences] ([Prefix], [LastNumber])
SELECT Prefix, MaxNumber FROM $legacy.[LatestCodeNumbers];

"@

# ---------- lab reports ----------
$labs = @(
    @{ Src = 'StoolFecalyses'; Cls = 'StoolFecalysisReport'; Type = 'StoolFecalysis'; Mode = 'std' },
    @{ Src = 'Urinalyses'; Cls = 'UrinalysisReport'; Type = 'Urinalysis'; Mode = 'std' },
    @{ Src = 'Hematologies'; Cls = 'HematologyReport'; Type = 'Hematology'; Mode = 'std' },
    @{ Src = 'Immunologies'; Cls = 'ImmunologyReport'; Type = 'Immunology'; Mode = 'std' },
    @{ Src = 'Serologies'; Cls = 'SerologyReport'; Type = 'Serology'; Mode = 'std' },
    @{ Src = 'PregnancyTests'; Cls = 'PregnancyTestReport'; Type = 'PregnancyTest'; Mode = 'std' },
    @{ Src = 'ClinicalChemistries'; Cls = 'ClinicalChemistryReport'; Type = 'ClinicalChemistry'; Mode = 'std' },
    @{ Src = 'ClinicalChemistries1'; Cls = 'ClinicalChemistry1Report'; Type = 'ClinicalChemistry1'; Mode = 'std' },
    @{ Src = 'ClinicalChemistries2'; Cls = 'ClinicalChemistry2Report'; Type = 'ClinicalChemistry2'; Mode = 'std' },
    @{ Src = 'APEs'; Cls = 'AnnualPhysicalExamReport'; Type = 'AnnualPhysicalExam'; Mode = 'ape' },
    @{ Src = 'MERs'; Cls = 'MedicalExaminationReport'; Type = 'MedicalExamination'; Mode = 'mer' }
)

# Read legacy column metadata (read-only).
$meta = & sqlcmd -S $Server -d $LegacyDatabase -E -C -h -1 -s '|' -W -Q "SET NOCOUNT ON; select t.name, c.name, ty.name from sys.columns c join sys.tables t on t.object_id=c.object_id join sys.types ty on ty.user_type_id=c.user_type_id where t.name in ('$(($labs | ForEach-Object { $_.Src }) -join "','")') order by t.name, c.column_id"
if ($LASTEXITCODE -ne 0) { throw 'Could not read legacy column metadata.' }
$cols = $meta | Where-Object { $_ -match '\|' } | ForEach-Object { $p = $_.Split('|'); [pscustomobject]@{ T = $p[0]; C = $p[1]; Ty = $p[2] } }

$common = @('Id', 'IsActive', 'CreatedByUserId', 'CreatedDate', 'UpdatedByUserId', 'UpdatedDate', 'PatientId', 'PatientRegistrationId', 'PatientName', 'Age', 'Photo')
$skipStd = $common + @('PatientCode', 'CompanyOrPhysician', 'Sex', 'DateRequested', 'Remarks', 'MedicalTechnologist', 'Pathologist')
$skipOutlier = $common + @('DateInputted', 'CompanyName', 'Gender', 'Remarks')

Emit '-- ===== Lab reports: header rows go to LabReports (new ids, mapped per source table) ====='
Emit ''

foreach ($lab in $labs) {
    $src = $lab.Src
    $isOutlier = $lab.Mode -ne 'std'
    $skip = if ($isOutlier) { $skipOutlier } else { $skipStd }
    $detail = @($cols | Where-Object { $_.T -eq $src -and $_.C -notin $skip })

    $header = [ordered]@{
        ReportType = "'$($lab.Type)'"
        PatientId = 'src.PatientId'
        PatientRegistrationId = 'src.PatientRegistrationId'
        PatientCode = 'src.PatientCode'
        PatientName = 'src.PatientName'
        Age = 'src.Age'
        Sex = 'src.Sex'
        CompanyOrPhysician = 'src.CompanyOrPhysician'
        DateRequested = 'src.DateRequested'
        Remarks = 'src.Remarks'
        MedicalTechnologist = 'src.MedicalTechnologist'
        Pathologist = 'src.Pathologist'
        CreatedAtUtc = 'src.CreatedAtUtc'
        CreatedByUserId = 'src.CreatedByUserId'
        UpdatedAtUtc = 'src.UpdatedAtUtc'
        UpdatedByUserId = 'src.UpdatedByUserId'
        IsDeleted = 'src.IsDeleted'
        DeletedAtUtc = 'src.DeletedAtUtc'
        DeletedByUserId = 'src.DeletedByUserId'
    }
    $audit = AuditCols 'soft'

    if ($isOutlier) {
        $dateCol = 's.DateInputted'
        $select = @(
            's.Id AS LegacyId',
            'COALESCE(s.PatientId, r.PatientId) AS PatientId',
            'r.Id AS PatientRegistrationId',
            'p.PatientCode',
            's.PatientName',
            's.Age',
            's.Gender AS Sex',
            's.CompanyName AS CompanyOrPhysician',
            "COALESCE($(U $dateCol), $(U 's.CreatedDate')) AS DateRequested",
            $(if ($lab.Mode -eq 'mer') { 's.Remarks' } else { 'CAST(NULL AS nvarchar(500)) AS Remarks' }),
            'CAST(NULL AS nvarchar(100)) AS MedicalTechnologist',
            'CAST(NULL AS nvarchar(100)) AS Pathologist'
        )
        $joinPatient = "JOIN $legacy.[Patients] p ON p.Id = COALESCE(s.PatientId, r.PatientId)"
    } else {
        $select = @(
            's.Id AS LegacyId',
            'COALESCE(s.PatientId, r.PatientId) AS PatientId',
            'r.Id AS PatientRegistrationId',
            's.PatientCode',
            's.PatientName',
            's.Age',
            's.Sex',
            's.CompanyOrPhysician',
            "COALESCE($(U 's.DateRequested'), $(U 's.CreatedDate')) AS DateRequested",
            $(if ($cols | Where-Object { $_.T -eq $src -and $_.C -eq 'Remarks' }) { 's.Remarks' } else { 'CAST(NULL AS nvarchar(500)) AS Remarks' }),
            's.MedicalTechnologist',
            's.Pathologist'
        )
        $joinPatient = "JOIN $legacy.[Patients] p ON p.Id = COALESCE(s.PatientId, r.PatientId)"
    }
    foreach ($k in $audit.Keys | Where-Object { $_ -ne 'IsActive' }) { $select += "$($audit[$k]) AS $k" }

    $hn = ($header.Keys | ForEach-Object { "[$_]" }) -join ', '
    $hv = ($header.Values) -join ', '
    $selectSql = ($select -join ",`r`n           ")

    Emit "-- $src -> LabReports ($($lab.Type)) + $($lab.Cls)s"
    Emit "TRUNCATE TABLE #map;"
    Emit "MERGE [LabReports] AS t"
    Emit "USING ("
    Emit "    SELECT $selectSql"
    Emit "    FROM $legacy.[$src] s"
    Emit "    LEFT JOIN $legacy.[PatientRegistrations] r ON r.Id = s.PatientRegistrationId"
    if ($joinPatient) { Emit "    $joinPatient" }
    Emit ") AS src ON 1 = 0"
    Emit "WHEN NOT MATCHED THEN INSERT ($hn)"
    Emit "    VALUES ($hv)"
    Emit "OUTPUT src.LegacyId, inserted.Id INTO #map (LegacyId, NewId);"
    Emit ''
    Emit "INSERT INTO #skipped SELECT '$src', s.Id, 'No matching patient for this lab row' FROM $legacy.[$src] s WHERE s.Id NOT IN (SELECT LegacyId FROM #map);"
    Emit ''

    if (-not $isOutlier) {
        Emit "INSERT INTO [LabReportPhotos] ([LabReportId], [Content]) SELECT m.NewId, s.Photo FROM $legacy.[$src] s JOIN #map m ON m.LegacyId = s.Id WHERE s.Photo IS NOT NULL;"
        Emit ''
    }

    $dn = (@('LabReportId') + ($detail | ForEach-Object { $_.C })) | ForEach-Object { "[$_]" }
    $dv = @('m.NewId') + ($detail | ForEach-Object { if ($_.Ty -eq 'nchar') { "RTRIM(s.[$($_.C)])" } else { "s.[$($_.C)]" } })
    Emit "INSERT INTO [$($lab.Cls)s] ($($dn -join ', '))"
    Emit "SELECT $($dv -join ', ')"
    Emit "FROM $legacy.[$src] s JOIN #map m ON m.LegacyId = s.Id;"
    Emit ''
    if ($src -eq 'StoolFecalyses') {
        Emit '-- The old Fecalysis form had one free-text Result; the new form has Remarks. Move that text across (into Remarks when the report has none, otherwise into Others).'
        Emit 'UPDATE r SET r.Remarks = s.Result'
        Emit 'FROM [LabReports] r JOIN [StoolFecalysisReports] s ON s.LabReportId = r.Id'
        Emit 'WHERE LTRIM(RTRIM(ISNULL(s.Result, N''''))) <> N'''' AND LTRIM(RTRIM(ISNULL(r.Remarks, N''''))) = N'''';'
        Emit ''
        Emit 'UPDATE s SET s.Others = s.Result'
        Emit 'FROM [StoolFecalysisReports] s JOIN [LabReports] r ON r.Id = s.LabReportId'
        Emit 'WHERE LTRIM(RTRIM(ISNULL(s.Result, N''''))) <> N'''' AND r.Remarks <> s.Result AND s.Others = N'''';'
        Emit ''
    }
}

Emit @"
-- ===== Summary =====
SELECT SourceTable AS SkippedSourceTable, LegacyId, Reason FROM #skipped ORDER BY SourceTable, LegacyId;

COMMIT TRANSACTION;
PRINT 'Migration committed. Run db/verify-migration.sql to compare row counts.';
"@

$sql = $out.ToString()
[IO.File]::WriteAllText((Join-Path $root 'db\migrate-from-legacy.sql'), $sql, (New-Object Text.UTF8Encoding($true)))

# ---------- verification script ----------
$pairs = @(
    @('ModuleTypes', 'ModuleTypes'), @('Modules', 'Modules'), @('Services', 'Services'), @('Users', 'Users'),
    @('UserPermissions', 'UserPermissions'), @('Companies', 'Companies'), @('CompanySetups', 'CompanySetups'),
    @('Departments', 'Departments'), @('Items', 'Items'), @('ItemLocations', 'ItemLocations'),
    @('ItemQuantities', 'ItemQuantities'), @('ServiceItemQuantities', 'ServiceItemQuantities'),
    @('Discounts', 'Discounts'), @('DiscountDetails', 'DiscountDetails'), @('Packages', 'Packages'),
    @('PackageServices', 'PackageServices'), @('Patients', 'Patients'), @('PatientRegistrations', 'PatientRegistrations'),
    @('PatientRegistrationServices', 'PatientRegistrationServices'), @('Payments', 'Payments'),
    @('ModuleDefaults', 'LabResultsDefaults')
)
$v = New-Object System.Text.StringBuilder
[void]$v.AppendLine("/* Row-count and sum checks, legacy vs new. GENERATED by tools/Generate-LegacyMigration.ps1.`r`n   sqlcmd -S <server> -d <target> -E -C -I -b -i db/verify-migration.sql -v Legacy=DiagnosticLabsDB */")
[void]$v.AppendLine("SET NOCOUNT ON;")
[void]$v.AppendLine("CREATE TABLE #r (Item nvarchar(100), LegacyValue decimal(38,4), NewValue decimal(38,4));")
foreach ($p in $pairs) {
    # Only legacy permission rows that grant access are migrated (see the UserPermissions insert above).
    $legacyWhere = switch ($p[0]) {
        'UserPermissions' { ' WHERE ViewOnly = 1 OR AllowCreate = 1 OR AllowEdit = 1 OR AllowDelete = 1 OR AllowPrint = 1' }
        'Companies' { ' WHERE Id <> 0' }   # the legacy WALK-IN row is not migrated
        default { '' }
    }
    [void]$v.AppendLine("INSERT #r SELECT '$($p[0]) rows', (SELECT COUNT(*) FROM [${dollar}(Legacy)].dbo.[$($p[1])]$legacyWhere), (SELECT COUNT(*) FROM [$($p[0])] ) ;")
}
[void]$v.AppendLine("INSERT #r SELECT 'LookupValues rows', (SELECT COUNT(*) FROM [${dollar}(Legacy)].dbo.DefaultValues) + (SELECT COUNT(*) FROM [${dollar}(Legacy)].dbo.SingleLineEntries) + (SELECT COUNT(*) FROM [${dollar}(Legacy)].dbo.MultiLineEntries), (SELECT COUNT(*) FROM LookupValues);")
[void]$v.AppendLine("INSERT #r SELECT 'Payments amount (sum)', (SELECT SUM(PaymentAmount) FROM [${dollar}(Legacy)].dbo.Payments), (SELECT SUM(PaymentAmount) FROM Payments);")
[void]$v.AppendLine("INSERT #r SELECT 'Registrations AmountDue (sum)', (SELECT SUM(AmountDue) FROM [${dollar}(Legacy)].dbo.PatientRegistrations), (SELECT SUM(AmountDue) FROM PatientRegistrations);")
[void]$v.AppendLine("INSERT #r SELECT 'Soft-deleted patients', (SELECT COUNT(*) FROM [${dollar}(Legacy)].dbo.Patients WHERE IsActive = 0), (SELECT COUNT(*) FROM Patients WHERE IsDeleted = 1);")
$labUnion = ($labs | ForEach-Object { "SELECT COUNT(*) c FROM [${dollar}(Legacy)].dbo.[$($_.Src)]" }) -join ' UNION ALL '
[void]$v.AppendLine("INSERT #r SELECT 'LabReports rows (all lab tables)', (SELECT SUM(c) FROM ($labUnion) x), (SELECT COUNT(*) FROM LabReports);")
foreach ($lab in $labs) {
    [void]$v.AppendLine("INSERT #r SELECT '$($lab.Cls)s rows', (SELECT COUNT(*) FROM [${dollar}(Legacy)].dbo.[$($lab.Src)]), (SELECT COUNT(*) FROM [$($lab.Cls)s]);")
}
[void]$v.AppendLine("SELECT Item, LegacyValue, NewValue, CASE WHEN LegacyValue = NewValue THEN 'ok' ELSE 'DIFFERENT' END AS Status FROM #r ORDER BY Item;")
[void]$v.AppendLine("-- Expected difference: Companies is equal (the WALK-IN row is kept); any DIFFERENT lab row count means rows were skipped (see the migration summary).")
[IO.File]::WriteAllText((Join-Path $root 'db\verify-migration.sql'), $v.ToString(), (New-Object Text.UTF8Encoding($true)))

"Wrote db\migrate-from-legacy.sql ($($sql.Length) chars) and db\verify-migration.sql"
